# <center>SAE BDD - Phase 2</center>

# Sommaire

## I - Rapport
- 1) Tables
- 2) Attributs
- 3) Clés
</ul>

## II - Script
- 1) Création des tables
- 2) Exemple avec le passager n°1
- 3) Alimentation des tables avec le contenu de <code>titanic_train.csv</code>
- 4) Commandes de réinitialisations
- 5) Script sous format texte

---

# I - Rapport

## 1) Tables
Dans la phase 2 de cette SAE, nous avons créé trois tables à partir du modèle de données proposé.<br>
Ces tables sont:

- **Ticket**: les informations pouvant être présentes sur le ticket d'un passager et qui nous renseignent sur son séjour à bord du *Titanic*.<br>
Les attributs utilisés sont le nom de l'individu (**Name**, <u>clé primaire</u>), sa classe de passager à bord du *Titanic* (**Pclass**), son numéro de ticket (**Ticket**) ainsi que son prix (**Fare**), son numéro de cabine s'il est connu (**Cabin**) et l'initiale du lieu d'embarcation (**Embarked**).<br><br>

- **Passager**: les informations sur le passager<br>
Les attributs utilisés sont l'identifiant du passager (**PassengerId**, <u>clé primaire</u>), le nom (**Name**, <u>clé étrangère</u>), l'âge (**Age**), le sexe de l'individu (**Sex**), ainsi que du nombre de proches s'il est accompagné: le nombre de frères/soeurs, d'époux/épouses (**Sibsp**) et de parents ou d'enfants (**Parch***) du passager.


- **Survivant**: les informations concernant la survie ou non du passager<br>
Les attributs utilisés sont donc l'identifiant du passager (**PassengerId**, <u>clé étrangère</u>), son nom (**Name**, <u>clé étrangère</u>) et un indicateur de sa survie (**Survived**).
</ul>

**<u>NB</u>: Sibsp** est l'abréviation de l'anglais "*Siblings and spouses*" qui se traduit "Frères/soeurs et époux/épouses", tandis que **Parch** signifie "*Parents and children*" se traduisant "Parents et enfants". **Pclass** est l'abréviation de "*Passenger class*", ce qui donne "Classe du passager" en français.<br><br>

Ainsi, nous avons:<br><br>
-Ticket (**Name**, Pclass, Ticket, Fare, Cabin, Embarked)<br>
-Passager (**PassengerId**, **Name**, Age, Sex, Sibsp, Parch)<br>
-Survivant (**PassengerId**, **Name**, Survived)<br><br>
Les clés primaires sont notées en **gras**.

## 2) Attributs
Ci-dessous, un tableau précisant les types de données de chaque attribut:<br>

|Attribut|Type|Exemple|Information sur la valeur
:--------|:---|:------|:------------------------
PassengerId|integer|1|
Survived|integer|0|0 = N'a pas survécu, 1 = A survécu (Non et Oui)
Pclass|integer|3|1 = 1ère, 2 = 2ème, 3 = 3ème (Classe)
Name|string|Braund, Mr. Owen Harris|
Sex|string|male|"male" ou "female"
Age|float|22|
Sibsp|integer|1|
Parch|integer|0|
Ticket|string|A/5 21171|
Fare|float|7.25|
Cabin|string||
Embarked|string|S|C = Cherbourg, Q = Queenstown, S = Southampton

## 3) Clés
### Clé primaires
Parmi ces tableaux, les <u>clé primaires</u> sont **Name** de la table *Ticket* et **PassengerId** de la table *Passager*.<br> Ces clés primaires vont êtres référencés dans les autres tables en tant que clés étrangères sachant que chaque valeur dans ces attributs sont distinctes et ne sont présentes que dans son tuple respectif. Elle n'apparaît donc pas plus d'une fois.
### Clé étrangères
**ticket.Name** est <u>clé étrangère</u> dans les tables *Passager* et *Survivant*, tandis que **passager.PassengerId** est <u>clé étrangère</u> dans *Survivant* seulement.<br>
L'existence de clés étrangères permet de faire la jointure entre les plusieurs tables/relations possédant une clé primaire associée à celle-ci.<br><br><br>

---

# II - Script

In [1]:
%load_ext sql

In [2]:
%sql postgresql://user1:pw2021@localhost/postgres

## 1) Création des tables

In [38]:
%%sql
CREATE TABLE ticket(Name varchar(100) primary key, Pclass int, Ticket varchar(20), 
                    Fare float, Cabin varchar(20), Embarked varchar(1));

CREATE TABLE passager(PassengerId int primary key, Name varchar(100), Sex varchar(6), Age float, SibSp int, Parch int, 
                      foreign key (Name) references ticket(Name));

CREATE TABLE survivant(PassengerId int, Name varchar(100), Survived int, 
                       foreign key (PassengerId) references passager(passengerid),
                       foreign key (Name) references ticket(name));

 * postgresql://user1:***@localhost/postgres
Done.
Done.
Done.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [39]:
%%sql
SELECT * from ticket;

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [40]:
%%sql
SELECT * from passager;

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [41]:
%%sql
SELECT * from survivant;

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [42]:
%%sql
SELECT * from passager natural join survivant natural join ticket;

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

## 2) Exemple avec les données du passager n°1

In [12]:
%%sql
INSERT INTO ticket VALUES ('Braund, Mr. Owen Harris', 3, 'A/5 21171', 7.25, null, 'S');
INSERT INTO passager VALUES (1,(select name from ticket), 'male', 22, 1, 0);
INSERT INTO survivant VALUES ((select passengerid from passager),(select name from ticket),0);

 * postgresql://user1:***@localhost/postgres
1 rows affected.
1 rows affected.
1 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [13]:
%%sql
SELECT * from ticket;

 * postgresql://user1:***@localhost/postgres
1 rows affected.

[('Braund, Mr. Owen Harris', 3, 'A/5 21171', 7.25, None, 'S')]

In [14]:
%%sql
SELECT * from passager;

 * postgresql://user1:***@localhost/postgres
1 rows affected.

[(1, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0)]

In [15]:
%%sql
SELECT * from survivant;

 * postgresql://user1:***@localhost/postgres
1 rows affected.

[(1, 'Braund, Mr. Owen Harris', 0)]

In [16]:
%%sql
SELECT * from passager natural join survivant natural join ticket;

 * postgresql://user1:***@localhost/postgres
1 rows affected.

[('Braund, Mr. Owen Harris', 1, 'male', 22.0, 1, 0, 0, 3, 'A/5 21171', 7.25, None, 'S')]

## 3) Alimentation des tables avec le contenu de <code>titanic_train.csv</code>

In [18]:
%%sql
\copy ticket from '/Users/Asus/Documents/ticket.txt'

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [32]:
%%sql
\copy passager from '/Users/Asus/Documents/passager.txt'

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [33]:
%%sql
\copy survivant from '/Users/Asus/Documents/survivant.txt'

 * postgresql://user1:***@localhost/postgres
0 rows affected.

[]

In [19]:
%%sql
select * from ticket;

 * postgresql://user1:***@localhost/postgres
891 rows affected.

[('Braund, Mr. Owen Harris', 3, 'A/5 21171', 7.25, '', 'S'),
 ('Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 1, 'PC 17599', 71.2833, 'C85', 'C'),
 ('Heikkinen, Miss. Laina', 3, 'STON/O2. 3101282', 7.925, '', 'S'),
 ('Futrelle, Mrs. Jacques Heath (Lily May Peel)', 1, '113803', 53.1, 'C123', 'S'),
 ('Allen, Mr. William Henry', 3, '373450', 8.05, '', 'S'),
 ('Moran, Mr. James', 3, '330877', 8.4583, '', 'Q'),
 ('McCarthy, Mr. Timothy J', 1, '17463', 51.8625, 'E46', 'S'),
 ('Palsson, Master. Gosta Leonard', 3, '349909', 21.075, '', 'S'),
 ('Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 3, '347742', 11.1333, '', 'S'),
 ('Nasser, Mrs. Nicholas (Adele Achem)', 2, '237736', 30.0708, '', 'C'),
 ('Sandstrom, Miss. Marguerite Rut', 3, 'PP 9549', 16.7, 'G6', 'S'),
 ('Bonnell, Miss. Elizabeth', 1, '113783', 26.55, 'C103', 'S'),
 ('Saundercock, Mr. William Henry', 3, 'A/5. 2151', 8.05, '', 'S'),
 ('Andersson, Mr. Anders Johan', 3, '347082', 31.275, '', 'S'),
 ('Vestrom, Miss. Hulda Amanda Adolfina', 3, '350406', 7.8542, '', 'S'),
 ('Hewlett, Mrs. (Mary D Kingcome) ', 2, '248706', 16.0, '', 'S'),
 ('Rice, Master. Eugene', 3, '382652', 29.125, '', 'Q'),
 ('Williams, Mr. Charles Eugene', 2, '244373', 13.0, '', 'S'),
 ('Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 3, '345763', 18.0, '', 'S'),
 ('Masselmani, Mrs. Fatima', 3, '2649', 7.225, '', 'C'),
 ('Fynney, Mr. Joseph J', 2, '239865', 26.0, '', 'S'),
 ('Beesley, Mr. Lawrence', 2, '248698', 13.0, 'D56', 'S'),
 ('McGowan, Miss. Anna "Annie"', 3, '330923', 8.0292, '', 'Q'),
 ('Sloper, Mr. William Thompson', 1, '113788', 35.5, 'A6', 'S'),
 ('Palsson, Miss. Torborg Danira', 3, '349909', 21.075, '', 'S'),
 ('Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 3, '347077', 31.3875, '', 'S'),
 ('Emir, Mr. Farred Chehab', 3, '2631', 7.225, '', 'C'),
 ('Fortune, Mr. Charles Alexander', 1, '19950', 263.0, 'C23 C25 C27', 'S'),
 ('O\'Dwyer, Miss. Ellen "Nellie"', 3, '330959', 7.8792, '', 'Q'),
 ('Todoroff, Mr. Lalio', 3, '349216', 7.8958, '', 'S'),
 ('Uruchurtu, Don. Manuel E', 1, 'PC 17601', 27.7208, '', 'C'),
 ('Spencer, Mrs. William Augustus (Marie Eugenie)', 1, 'PC 17569', 146.5208, 'B78', 'C'),
 ('Glynn, Miss. Mary Agatha', 3, '335677', 7.75, '', 'Q'),
 ('Wheadon, Mr. Edward H', 2, 'C.A. 24579', 10.5, '', 'S'),
 ('Meyer, Mr. Edgar Joseph', 1, 'PC 17604', 82.1708, '', 'C'),
 ('Holverson, Mr. Alexander Oskar', 1, '113789', 52.0, '', 'S'),
 ('Mamee, Mr. Hanna', 3, '2677', 7.2292, '', 'C'),
 ('Cann, Mr. Ernest Charles', 3, 'A./5. 2152', 8.05, '', 'S'),
 ('Vander Planke, Miss. Augusta Maria', 3, '345764', 18.0, '', 'S'),
 ('Nicola-Yarred, Miss. Jamila', 3, '2651', 11.2417, '', 'C'),
 ('Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 3, '7546', 9.475, '', 'S'),
 ('Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 2, '11668', 21.0, '', 'S'),
 ('Kraeff, Mr. Theodor', 3, '349253', 7.8958, '', 'C'),
 ('Laroche, Miss. Simonne Marie Anne Andree', 2, 'SC/Paris 2123', 41.5792, '', 'C'),
 ('Devaney, Miss. Margaret Delia', 3, '330958', 7.8792, '', 'Q'),
 ('Rogers, Mr. William John', 3, 'S.C./A.4. 23567', 8.05, '', 'S'),
 ('Lennon, Mr. Denis', 3, '370371', 15.5, '', 'Q'),
 ("O'Driscoll, Miss. Bridget", 3, '14311', 7.75, '', 'Q'),
 ('Samaan, Mr. Youssef', 3, '2662', 21.6792, '', 'C'),
 ('Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 3, '349237', 17.8, '', 'S'),
 ('Panula, Master. Juha Niilo', 3, '3101295', 39.6875, '', 'S'),
 ('Nosworthy, Mr. Richard Cater', 3, 'A/4. 39886', 7.8, '', 'S'),
 ('Harper, Mrs. Henry Sleeper (Myna Haxtun)', 1, 'PC 17572', 76.7292, 'D33', 'C'),
 ('Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 2, '2926', 26.0, '', 'S'),
 ('Ostby, Mr. Engelhart Cornelius', 1, '113509', 61.9792, 'B30', 'C'),
 ('Woolner, Mr. Hugh', 1, '19947', 35.5, 'C52', 'S'),
 ('Rugg, Miss. Emily', 2, 'C.A. 31026', 10.5, '', 'S'),
 ('Novel, Mr. Mansouer', 3, '2697', 7.2292, '', 'C'),
 ('West, Miss. Constance Mirium', 2, 'C.A. 34651', 27.75, '', 'S'),
 ('Goodwin, Master. William Frederick', 3, 'CA 2144', 46.9, '', 'S'),
 ('Sirayanian, Mr. Orsen', 3, '2669', 7.2292, '', 'C'),
 ('Icard, Miss. Amelie', 1, '113572', 80.0, 'B28', ''),
 ('Harris, Mr. Henry Birkhardt', 1, '36973', 83.475, 'C83', 'S'),
 ('Skoog, Master. Harald', 3, '347088', 27.9, '', 'S'),
 ('Stewart, Mr. Albert A', 1, 'PC 17605', 27.7208, '', 'C'),
 ('Moubarek, Master. Gerios', 3, '2661', 15.2458, '', 'C'),
 ('Nye, Mrs. (Elizabeth Ramell)', 2, 'C.A. 29395', 10.5, 'F33', 'S'),
 ('Crease, Mr. Ernest James', 3, 'S.P. 3464', 8.1583, '', 'S'),
 ('Andersson, Miss. Erna Alexandra', 3, '3101281', 7.925, '', 'S'),
 ('Kink, Mr. Vincenz', 3, '315151', 8.6625, '', 'S'),
 ('Jenkin, Mr. Stephen Curnow', 2, 'C.A. 33111', 10.5, '', 'S'),
 ('Goodwin, Miss. Lillian Amy', 3, 'CA 2144', 46.9, '', 'S'),
 ('Hood, Mr. Ambrose Jr', 2, 'S.O.C. 14879', 73.5, '', 'S'),
 ('Chronopoulos, Mr. Apostolos', 3, '2680', 14.4542, '', 'C'),
 ('Bing, Mr. Lee', 3, '1601', 56.4958, '', 'S'),
 ('Moen, Mr. Sigurd Hansen', 3, '348123', 7.65, 'F G73', 'S'),
 ('Staneff, Mr. Ivan', 3, '349208', 7.8958, '', 'S'),
 ('Moutal, Mr. Rahamin Haim', 3, '374746', 8.05, '', 'S'),
 ('Caldwell, Master. Alden Gates', 2, '248738', 29.0, '', 'S'),
 ('Dowdell, Miss. Elizabeth', 3, '364516', 12.475, '', 'S'),
 ('Waelens, Mr. Achille', 3, '345767', 9.0, '', 'S'),
 ('Sheerlinck, Mr. Jan Baptist', 3, '345779', 9.5, '', 'S'),
 ('McDermott, Miss. Brigdet Delia', 3, '330932', 7.7875, '', 'Q'),
 ('Carrau, Mr. Francisco M', 1, '113059', 47.1, '', 'S'),
 ('Ilett, Miss. Bertha', 2, 'SO/C 14885', 10.5, '', 'S'),
 ('Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 3, '3101278', 15.85, '', 'S'),
 ('Ford, Mr. William Neal', 3, 'W./C. 6608', 34.375, '', 'S'),
 ('Slocovski, Mr. Selman Francis', 3, 'SOTON/OQ 392086', 8.05, '', 'S'),
 ('Fortune, Miss. Mabel Helen', 1, '19950', 263.0, 'C23 C25 C27', 'S'),
 ('Celotti, Mr. Francesco', 3, '343275', 8.05, '', 'S'),
 ('Christmann, Mr. Emil', 3, '343276', 8.05, '', 'S'),
 ('Andreasson, Mr. Paul Edvin', 3, '347466', 7.8542, '', 'S'),
 ('Chaffee, Mr. Herbert Fuller', 1, 'W.E.P. 5734', 61.175, 'E31', 'S'),
 ('Dean, Mr. Bertram Frank', 3, 'C.A. 2315', 20.575, '', 'S'),
 ('Coxon, Mr. Daniel', 3, '364500', 7.25, '', 'S'),
 ('Shorney, Mr. Charles Joseph', 3, '374910', 8.05, '', 'S'),
 ('Goldschmidt, Mr. George B', 1, 'PC 17754', 34.6542, 'A5', 'C'),
 ('Greenfield, Mr. William Bertram', 1, 'PC 17759', 63.3583, 'D10 D12', 'C'),
 ('Doling, Mrs. John T (Ada Julia Bone)', 2, '231919', 23.0, '', 'S'),
 ('Kantor, Mr. Sinai', 2, '244367', 26.0, '', 'S'),
 ('Petranec, Miss. Matilda', 3, '349245', 7.8958, '', 'S'),
 ('Petroff, Mr. Pastcho ("Pentcho")', 3, '349215', 7.8958, '', 'S'),
 ('White, Mr. Richard Frasar', 1, '35281', 77.2875, 'D26', 'S'),
 ('Johansson, Mr. Gustaf Joel', 3, '7540', 8.6542, '', 'S'),
 ('Gustafsson, Mr. Anders Vilhelm', 3, '3101276', 7.925, '', 'S'),
 ('Mionoff, Mr. Stoytcho', 3, '349207', 7.8958, '', 'S'),
 ('Salkjelsvik, Miss. Anna Kristine', 3, '343120', 7.65, '', 'S'),
 ('Moss, Mr. Albert Johan', 3, '312991', 7.775, '', 'S'),
 ('Rekic, Mr. Tido', 3, '349249', 7.8958, '', 'S'),
 ('Moran, Miss. Bertha', 3, '371110', 24.15, '', 'Q'),
 ('Porter, Mr. Walter Chamberlain', 1, '110465', 52.0, 'C110', 'S'),
 ('Zabour, Miss. Hileni', 3, '2665', 14.4542, '', 'C'),
 ('Barton, Mr. David John', 3, '324669', 8.05, '', 'S'),
 ('Jussila, Miss. Katriina', 3, '4136', 9.825, '', 'S'),
 ('Attalah, Miss. Malake', 3, '2627', 14.4583, '', 'C'),
 ('Pekoniemi, Mr. Edvard', 3, 'STON/O 2. 3101294', 7.925, '', 'S'),
 ('Connors, Mr. Patrick', 3, '370369', 7.75, '', 'Q'),
 ('Turpin, Mr. William John Robert', 2, '11668', 21.0, '', 'S'),
 ('Baxter, Mr. Quigg Edmond', 1, 'PC 17558', 247.5208, 'B58 B60', 'C'),
 ('Andersson, Miss. Ellis Anna Maria', 3, '347082', 31.275, '', 'S'),
 ('Hickman, Mr. Stanley George', 2, 'S.O.C. 14879', 73.5, '', 'S'),
 ('Moore, Mr. Leonard Charles', 3, 'A4. 54510', 8.05, '', 'S'),
 ('Nasser, Mr. Nicholas', 2, '237736', 30.0708, '', 'C'),
 ('Webber, Miss. Susan', 2, '27267', 13.0, 'E101', 'S'),
 ('White, Mr. Percival Wayland', 1, '35281', 77.2875, 'D26', 'S'),
 ('Nicola-Yarred, Master. Elias', 3, '2651', 11.2417, '', 'C'),
 ('McMahon, Mr. Martin', 3, '370372', 7.75, '', 'Q'),
 ('Madsen, Mr. Fridtjof Arne', 3, 'C 17369', 7.1417, '', 'S'),
 ('Peter, Miss. Anna', 3, '2668', 22.3583, 'F E69', 'C'),
 ('Ekstrom, Mr. Johan', 3, '347061', 6.975, '', 'S'),
 ('Drazenoic, Mr. Jozef', 3, '349241', 7.8958, '', 'C'),
 ('Coelho, Mr. Domingos Fernandeo', 3, 'SOTON/O.Q. 3101307', 7.05, '', 'S'),
 ('Robins, Mrs. Alexander A (Grace Charity Laury)', 3, 'A/5. 3337', 14.5, '', 'S'),
 ('Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 2, '228414', 26.0, '', 'S'),
 ('Sobey, Mr. Samuel James Hayden', 2, 'C.A. 29178', 13.0, '', 'S'),
 ('Richard, Mr. Emile', 2, 'SC/PARIS 2133', 15.0458, '', 'C'),
 ('Newsom, Miss. Helen Monypeny', 1, '11752', 26.2833, 'D47', 'S'),
 ('Futrelle, Mr. Jacques Heath', 1, '113803', 53.1, 'C123', 'S'),
 ('Osen, Mr. Olaf Elon', 3, '7534', 9.2167, '', 'S'),
 ('Giglio, Mr. Victor', 1, 'PC 17593', 79.2, 'B86', 'C'),
 ('Boulos, Mrs. Joseph (Sultana)', 3, '2678', 15.2458, '', 'C'),
 ('Nysten, Miss. Anna Sofia', 3, '347081', 7.75, '', 'S'),
 ('Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 3, 'STON/O2. 3101279', 15.85, '', 'S'),
 ('Burke, Mr. Jeremiah', 3, '365222', 6.75, '', 'Q'),
 ('Andrew, Mr. Edgardo Samuel', 2, '231945', 11.5, '', 'S'),
 ('Nicholls, Mr. Joseph Charles', 2, 'C.A. 33112', 36.75, '', 'S'),
 ('Andersson, Mr. August Edvard ("Wennerstrom")', 3, '350043', 7.7958, '', 'S'),
 ('Ford, Miss. Robina Maggie "Ruby"', 3, 'W./C. 6608', 34.375, '', 'S'),
 ('Navratil, Mr. Michel ("Louis M Hoffman")', 2, '230080', 26.0, 'F2', 'S'),
 ('Byles, Rev. Thomas Roussel Davids', 2, '244310', 13.0, '', 'S'),
 ('Bateman, Rev. Robert James', 2, 'S.O.P. 1166', 12.525, '', 'S'),
 ('Pears, Mrs. Thomas (Edith Wearne)', 1, '113776', 66.6, 'C2', 'S'),
 ('Meo, Mr. Alfonzo', 3, 'A.5. 11206', 8.05, '', 'S'),
 ('van Billiard, Mr. Austin Blyler', 3, 'A/5. 851', 14.5, '', 'S'),
 ('Olsen, Mr. Ole Martin', 3, 'Fa 265302', 7.3125, '', 'S'),
 ('Williams, Mr. Charles Duane', 1, 'PC 17597', 61.3792, '', 'C'),
 ('Gilnagh, Miss. Katherine "Katie"', 3, '35851', 7.7333, '', 'Q'),
 ('Corn, Mr. Harry', 3, 'SOTON/OQ 392090', 8.05, '', 'S'),
 ('Smiljanic, Mr. Mile', 3, '315037', 8.6625, '', 'S'),
 ('Sage, Master. Thomas Henry', 3, 'CA. 2343', 69.55, '', 'S'),
 ('Cribb, Mr. John Hatfield', 3, '371362', 16.1, '', 'S'),
 ('Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 2, 'C.A. 33595', 15.75, '', 'S'),
 ('Bengtsson, Mr. John Viktor', 3, '347068', 7.775, '', 'S'),
 ('Calic, Mr. Jovo', 3, '315093', 8.6625, '', 'S'),
 ('Panula, Master. Eino Viljami', 3, '3101295', 39.6875, '', 'S'),
 ('Goldsmith, Master. Frank John William "Frankie"', 3, '363291', 20.525, '', 'S'),
 ('Chibnall, Mrs. (Edith Martha Bowerman)', 1, '113505', 55.0, 'E33', 'S'),
 ('Skoog, Mrs. William (Anna Bernhardina Karlsson)', 3, '347088', 27.9, '', 'S'),
 ('Baumann, Mr. John D', 1, 'PC 17318', 25.925, '', 'S'),
 ('Ling, Mr. Lee', 3, '1601', 56.4958, '', 'S'),
 ('Van der hoef, Mr. Wyckoff', 1, '111240', 33.5, 'B19', 'S'),
 ('Rice, Master. Arthur', 3, '382652', 29.125, '', 'Q'),
 ('Johnson, Miss. Eleanor Ileen', 3, '347742', 11.1333, '', 'S'),
 ('Sivola, Mr. Antti Wilhelm', 3, 'STON/O 2. 3101280', 7.925, '', 'S'),
 ('Smith, Mr. James Clinch', 1, '17764', 30.6958, 'A7', 'C'),
 ('Klasen, Mr. Klas Albin', 3, '350404', 7.8542, '', 'S'),
 ('Lefebre, Master. Henry Forbes', 3, '4133', 25.4667, '', 'S'),
 ('Isham, Miss. Ann Elizabeth', 1, 'PC 17595', 28.7125, 'C49', 'C'),
 ('Hale, Mr. Reginald', 2, '250653', 13.0, '', 'S'),
 ('Leonard, Mr. Lionel', 3, 'LINE', 0.0, '', 'S'),
 ('Sage, Miss. Constance Gladys', 3, 'CA. 2343', 69.55, '', 'S'),
 ('Pernot, Mr. Rene', 2, 'SC/PARIS 2131', 15.05, '', 'C'),
 ('Asplund, Master. Clarence Gustaf Hugo', 3, '347077', 31.3875, '', 'S'),
 ('Becker, Master. Richard F', 2, '230136', 39.0, 'F4', 'S'),
 ('Kink-Heilmann, Miss. Luise Gretchen', 3, '315153', 22.025, '', 'S'),
 ('Rood, Mr. Hugh Roscoe', 1, '113767', 50.0, 'A32', 'S'),
 ('O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 3, '370365', 15.5, '', 'Q'),
 ('Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 1, '111428', 26.55, '', 'S'),
 ('Bourke, Mr. John', 3, '364849', 15.5, '', 'Q'),
 ('Turcin, Mr. Stjepan', 3, '349247', 7.8958, '', 'S'),
 ('Pinsky, Mrs. (Rosa)', 2, '234604', 13.0, '', 'S'),
 ('Carbines, Mr. William', 2, '28424', 13.0, '', 'S'),
 ('Andersen-Jensen, Miss. Carla Christine Nielsine', 3, '350046', 7.8542, '', 'S'),
 ('Navratil, Master. Michel M', 2, '230080', 26.0, 'F2', 'S'),
 ('Brown, Mrs. James Joseph (Margaret Tobin)', 1, 'PC 17610', 27.7208, 'B4', 'C'),
 ('Lurette, Miss. Elise', 1, 'PC 17569', 146.5208, 'B80', 'C'),
 ('Mernagh, Mr. Robert', 3, '368703', 7.75, '', 'Q'),
 ('Olsen, Mr. Karl Siegwart Andreas', 3, '4579', 8.4042, '', 'S'),
 ('Madigan, Miss. Margaret "Maggie"', 3, '370370', 7.75, '', 'Q'),
 ('Yrois, Miss. Henriette ("Mrs Harbeck")', 2, '248747', 13.0, '', 'S'),
 ('Vande Walle, Mr. Nestor Cyriel', 3, '345770', 9.5, '', 'S'),
 ('Sage, Mr. Frederick', 3, 'CA. 2343', 69.55, '', 'S'),
 ('Johanson, Mr. Jakob Alfred', 3, '3101264', 6.4958, '', 'S'),
 ('Youseff, Mr. Gerious', 3, '2628', 7.225, '', 'C'),
 ('Cohen, Mr. Gurshon "Gus"', 3, 'A/5 3540', 8.05, '', 'S'),
 ('Strom, Miss. Telma Matilda', 3, '347054', 10.4625, 'G6', 'S'),
 ('Backstrom, Mr. Karl Alfred', 3, '3101278', 15.85, '', 'S'),
 ('Albimona, Mr. Nassef Cassem', 3, '2699', 18.7875, '', 'C'),
 ('Carr, Miss. Helen "Ellen"', 3, '367231', 7.75, '', 'Q'),
 ('Blank, Mr. Henry', 1, '112277', 31.0, 'A31', 'C'),
 ('Ali, Mr. Ahmed', 3, 'SOTON/O.Q. 3101311', 7.05, '', 'S'),
 ('Cameron, Miss. Clear Annie', 2, 'F.C.C. 13528', 21.0, '', 'S'),
 ('Perkin, Mr. John Henry', 3, 'A/5 21174', 7.25, '', 'S'),
 ('Givard, Mr. Hans Kristensen', 2, '250646', 13.0, '', 'S'),
 ('Kiernan, Mr. Philip', 3, '367229', 7.75, '', 'Q'),
 ('Newell, Miss. Madeleine', 1, '35273', 113.275, 'D36', 'C'),
 ('Honkanen, Miss. Eliina', 3, 'STON/O2. 3101283', 7.925, '', 'S'),
 ('Jacobsohn, Mr. Sidney Samuel', 2, '243847', 27.0, '', 'S'),
 ('Bazzani, Miss. Albina', 1, '11813', 76.2917, 'D15', 'C'),
 ('Harris, Mr. Walter', 2, 'W/C 14208', 10.5, '', 'S'),
 ('Sunderland, Mr. Victor Francis', 3, 'SOTON/OQ 392089', 8.05, '', 'S'),
 ('Bracken, Mr. James H', 2, '220367', 13.0, '', 'S'),
 ('Green, Mr. George Henry', 3, '21440', 8.05, '', 'S'),
 ('Nenkoff, Mr. Christo', 3, '349234', 7.8958, '', 'S'),
 ('Hoyt, Mr. Frederick Maxfield', 1, '19943', 90.0, 'C93', 'S'),
 ('Berglund, Mr. Karl Ivar Sven', 3, 'PP 4348', 9.35, '', 'S'),
 ('Mellors, Mr. William John', 2, 'SW/PP 751', 10.5, '', 'S'),
 ('Lovell, Mr. John Hall ("Henry")', 3, 'A/5 21173', 7.25, '', 'S'),
 ('Fahlstrom, Mr. Arne Jonas', 2, '236171', 13.0, '', 'S'),
 ('Lefebre, Miss. Mathilde', 3, '4133', 25.4667, '', 'S'),
 ('Harris, Mrs. Henry Birkhardt (Irene Wallach)', 1, '36973', 83.475, 'C83', 'S'),
 ('Larsson, Mr. Bengt Edvin', 3, '347067', 7.775, '', 'S'),
 ('Sjostedt, Mr. Ernst Adolf', 2, '237442', 13.5, '', 'S'),
 ('Asplund, Miss. Lillian Gertrud', 3, '347077', 31.3875, '', 'S'),
 ('Leyson, Mr. Robert William Norman', 2, 'C.A. 29566', 10.5, '', 'S'),
 ('Harknett, Miss. Alice Phoebe', 3, 'W./C. 6609', 7.55, '', 'S'),
 ('Hold, Mr. Stephen', 2, '26707', 26.0, '', 'S'),
 ('Collyer, Miss. Marjorie "Lottie"', 2, 'C.A. 31921', 26.25, '', 'S'),
 ('Pengelly, Mr. Frederick William', 2, '28665', 10.5, '', 'S'),
 ('Hunt, Mr. George Henry', 2, 'SCO/W 1585', 12.275, '', 'S'),
 ('Zabour, Miss. Thamine', 3, '2665', 14.4542, '', 'C'),
 ('Murphy, Miss. Katherine "Kate"', 3, '367230', 15.5, '', 'Q'),
 ('Coleridge, Mr. Reginald Charles', 2, 'W./C. 14263', 10.5, '', 'S'),
 ('Maenpaa, Mr. Matti Alexanteri', 3, 'STON/O 2. 3101275', 7.125, '', 'S'),
 ('Attalah, Mr. Sleiman', 3, '2694', 7.225, '', 'C'),
 ('Minahan, Dr. William Edward', 1, '19928', 90.0, 'C78', 'Q'),
 ('Lindahl, Miss. Agda Thorilda Viktoria', 3, '347071', 7.775, '', 'S'),
 ('Hamalainen, Mrs. William (Anna)', 2, '250649', 14.5, '', 'S'),
 ('Beckwith, Mr. Richard Leonard', 1, '11751', 52.5542, 'D35', 'S'),
 ('Carter, Rev. Ernest Courtenay', 2, '244252', 26.0, '', 'S'),
 ('Reed, Mr. James George', 3, '362316', 7.25, '', 'S'),
 ('Strom, Mrs. Wilhelm (Elna Matilda Persson)', 3, '347054', 10.4625, 'G6', 'S'),
 ('Stead, Mr. William Thomas', 1, '113514', 26.55, 'C87', 'S'),
 ('Lobb, Mr. William Arthur', 3, 'A/5. 3336', 16.1, '', 'S'),
 ('Rosblom, Mrs. Viktor (Helena Wilhelmina)', 3, '370129', 20.2125, '', 'S'),
 ('Touma, Mrs. Darwis (Hanne Youssef Razi)', 3, '2650', 15.2458, '', 'C'),
 ('Thorne, Mrs. Gertrude Maybelle', 1, 'PC 17585', 79.2, '', 'C'),
 ('Cherry, Miss. Gladys', 1, '110152', 86.5, 'B77', 'S'),
 ('Ward, Miss. Anna', 1, 'PC 17755', 512.3292, '', 'C'),
 ('Parrish, Mrs. (Lutie Davis)', 2, '230433', 26.0, '', 'S'),
 ('Smith, Mr. Thomas', 3, '384461', 7.75, '', 'Q'),
 ('Asplund, Master. Edvin Rojj Felix', 3, '347077', 31.3875, '', 'S'),
 ('Taussig, Mr. Emil', 1, '110413', 79.65, 'E67', 'S'),
 ('Harrison, Mr. William', 1, '112059', 0.0, 'B94', 'S'),
 ('Henry, Miss. Delia', 3, '382649', 7.75, '', 'Q'),
 ('Reeves, Mr. David', 2, 'C.A. 17248', 10.5, '', 'S'),
 ('Panula, Mr. Ernesti Arvid', 3, '3101295', 39.6875, '', 'S'),
 ('Persson, Mr. Ernst Ulrik', 3, '347083', 7.775, '', 'S'),
 ('Graham, Mrs. William Thompson (Edith Junkins)', 1, 'PC 17582', 153.4625, 'C125', 'S'),
 ('Bissette, Miss. Amelia', 1, 'PC 17760', 135.6333, 'C99', 'S'),
 ('Cairns, Mr. Alexander', 1, '113798', 31.0, '', 'S'),
 ('Tornquist, Mr. William Henry', 3, 'LINE', 0.0, '', 'S'),
 ('Mellinger, Mrs. (Elizabeth Anne Maidment)', 2, '250644', 19.5, '', 'S'),
 ('Natsch, Mr. Charles H', 1, 'PC 17596', 29.7, 'C118', 'C'),
 ('Healy, Miss. Hanora "Nora"', 3, '370375', 7.75, '', 'Q'),
 ('Andrews, Miss. Kornelia Theodosia', 1, '13502', 77.9583, 'D7', 'S'),
 ('Lindblom, Miss. Augusta Charlotta', 3, '347073', 7.75, '', 'S'),
 ('Parkes, Mr. Francis "Frank"', 2, '239853', 0.0, '', 'S'),
 ('Rice, Master. Eric', 3, '382652', 29.125, '', 'Q'),
 ('Abbott, Mrs. Stanton (Rosa Hunt)', 3, 'C.A. 2673', 20.25, '', 'S'),
 ('Duane, Mr. Frank', 3, '336439', 7.75, '', 'Q'),
 ('Olsson, Mr. Nils Johan Goransson', 3, '347464', 7.8542, '', 'S'),
 ('de Pelsmaeker, Mr. Alfons', 3, '345778', 9.5, '', 'S'),
 ('Dorking, Mr. Edward Arthur', 3, 'A/5. 10482', 8.05, '', 'S'),
 ('Smith, Mr. Richard William', 1, '113056', 26.0, 'A19', 'S'),
 ('Stankovic, Mr. Ivan', 3, '349239', 8.6625, '', 'C'),
 ('de Mulder, Mr. Theodore', 3, '345774', 9.5, '', 'S'),
 ('Naidenoff, Mr. Penko', 3, '349206', 7.8958, '', 'S'),
 ('Hosono, Mr. Masabumi', 2, '237798', 13.0, '', 'S'),
 ('Connolly, Miss. Kate', 3, '370373', 7.75, '', 'Q'),
 ('Barber, Miss. Ellen "Nellie"', 1, '19877', 78.85, '', 'S'),
 ('Bishop, Mrs. Dickinson H (Helen Walton)', 1, '11967', 91.0792, 'B49', 'C'),
 ('Levy, Mr. Rene Jacques', 2, 'SC/Paris 2163', 12.875, 'D', 'C'),
 ('Haas, Miss. Aloisia', 3, '349236', 8.85, '', 'S'),
 ('Mineff, Mr. Ivan', 3, '349233', 7.8958, '', 'S'),
 ('Lewy, Mr. Ervin G', 1, 'PC 17612', 27.7208, '', 'C'),
 ('Hanna, Mr. Mansour', 3, '2693', 7.2292, '', 'C'),
 ('Allison, Miss. Helen Loraine', 1, '113781', 151.55, 'C22 C26', 'S'),
 ('Saalfeld, Mr. Adolphe', 1, '19988', 30.5, 'C106', 'S'),
 ('Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 1, 'PC 17558', 247.5208, 'B58 B60', 'C'),
 ('Kelly, Miss. Anna Katherine "Annie Kate"', 3, '9234', 7.75, '', 'Q'),
 ('McCoy, Mr. Bernard', 3, '367226', 23.25, '', 'Q'),
 ('Johnson, Mr. William Cahoone Jr', 3, 'LINE', 0.0, '', 'S'),
 ('Keane, Miss. Nora A', 2, '226593', 12.35, 'E101', 'Q'),
 ('Williams, Mr. Howard Hugh "Harry"', 3, 'A/5 2466', 8.05, '', 'S'),
 ('Allison, Master. Hudson Trevor', 1, '113781', 151.55, 'C22 C26', 'S'),
 ('Fleming, Miss. Margaret', 1, '17421', 110.8833, '', 'C'),
 ('Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 1, 'PC 17758', 108.9, 'C65', 'C'),

In [34]:
%%sql
select * from passager;

 * postgresql://user1:***@localhost/postgres
891 rows affected.

[(1, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0),
 (2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0),
 (3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0),
 (4, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 1, 0),
 (5, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0),
 (6, 'Moran, Mr. James', 'male', 0.0, 0, 0),
 (7, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0),
 (8, 'Palsson, Master. Gosta Leonard', 'male', 2.0, 3, 1),
 (9, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female', 27.0, 0, 2),
 (10, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0, 1, 0),
 (11, 'Sandstrom, Miss. Marguerite Rut', 'female', 4.0, 1, 1),
 (12, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 0, 0),
 (13, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0),
 (14, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5),
 (15, 'Vestrom, Miss. Hulda Amanda Adolfina', 'female', 14.0, 0, 0),
 (16, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0, 0),
 (17, 'Rice, Master. Eugene', 'male', 2.0, 4, 1),
 (18, 'Williams, Mr. Charles Eugene', 'male', 0.0, 0, 0),
 (19, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female', 31.0, 1, 0),
 (20, 'Masselmani, Mrs. Fatima', 'female', 0.0, 0, 0),
 (21, 'Fynney, Mr. Joseph J', 'male', 35.0, 0, 0),
 (22, 'Beesley, Mr. Lawrence', 'male', 34.0, 0, 0),
 (23, 'McGowan, Miss. Anna "Annie"', 'female', 15.0, 0, 0),
 (24, 'Sloper, Mr. William Thompson', 'male', 28.0, 0, 0),
 (25, 'Palsson, Miss. Torborg Danira', 'female', 8.0, 3, 1),
 (26, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female', 38.0, 1, 5),
 (27, 'Emir, Mr. Farred Chehab', 'male', 0.0, 0, 0),
 (28, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 3, 2),
 (29, 'O\'Dwyer, Miss. Ellen "Nellie"', 'female', 0.0, 0, 0),
 (30, 'Todoroff, Mr. Lalio', 'male', 0.0, 0, 0),
 (31, 'Uruchurtu, Don. Manuel E', 'male', 40.0, 0, 0),
 (32, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'female', 0.0, 1, 0),
 (33, 'Glynn, Miss. Mary Agatha', 'female', 0.0, 0, 0),
 (34, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0),
 (35, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 1, 0),
 (36, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 1, 0),
 (37, 'Mamee, Mr. Hanna', 'male', 0.0, 0, 0),
 (38, 'Cann, Mr. Ernest Charles', 'male', 21.0, 0, 0),
 (39, 'Vander Planke, Miss. Augusta Maria', 'female', 18.0, 2, 0),
 (40, 'Nicola-Yarred, Miss. Jamila', 'female', 14.0, 1, 0),
 (41, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female', 40.0, 1, 0),
 (42, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female', 27.0, 1, 0),
 (43, 'Kraeff, Mr. Theodor', 'male', 0.0, 0, 0),
 (44, 'Laroche, Miss. Simonne Marie Anne Andree', 'female', 3.0, 1, 2),
 (45, 'Devaney, Miss. Margaret Delia', 'female', 19.0, 0, 0),
 (46, 'Rogers, Mr. William John', 'male', 0.0, 0, 0),
 (47, 'Lennon, Mr. Denis', 'male', 0.0, 1, 0),
 (48, "O'Driscoll, Miss. Bridget", 'female', 0.0, 0, 0),
 (49, 'Samaan, Mr. Youssef', 'male', 0.0, 2, 0),
 (50, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female', 18.0, 1, 0),
 (51, 'Panula, Master. Juha Niilo', 'male', 7.0, 4, 1),
 (52, 'Nosworthy, Mr. Richard Cater', 'male', 21.0, 0, 0),
 (53, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 1, 0),
 (54, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female', 29.0, 1, 0),
 (55, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1),
 (56, 'Woolner, Mr. Hugh', 'male', 0.0, 0, 0),
 (57, 'Rugg, Miss. Emily', 'female', 21.0, 0, 0),
 (58, 'Novel, Mr. Mansouer', 'male', 28.5, 0, 0),
 (59, 'West, Miss. Constance Mirium', 'female', 5.0, 1, 2),
 (60, 'Goodwin, Master. William Frederick', 'male', 11.0, 5, 2),
 (61, 'Sirayanian, Mr. Orsen', 'male', 22.0, 0, 0),
 (62, 'Icard, Miss. Amelie', 'female', 38.0, 0, 0),
 (63, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 1, 0),
 (64, 'Skoog, Master. Harald', 'male', 4.0, 3, 2),
 (65, 'Stewart, Mr. Albert A', 'male', 0.0, 0, 0),
 (66, 'Moubarek, Master. Gerios', 'male', 0.0, 1, 1),
 (67, 'Nye, Mrs. (Elizabeth Ramell)', 'female', 29.0, 0, 0),
 (68, 'Crease, Mr. Ernest James', 'male', 19.0, 0, 0),
 (69, 'Andersson, Miss. Erna Alexandra', 'female', 17.0, 4, 2),
 (70, 'Kink, Mr. Vincenz', 'male', 26.0, 2, 0),
 (71, 'Jenkin, Mr. Stephen Curnow', 'male', 32.0, 0, 0),
 (72, 'Goodwin, Miss. Lillian Amy', 'female', 16.0, 5, 2),
 (73, 'Hood, Mr. Ambrose Jr', 'male', 21.0, 0, 0),
 (74, 'Chronopoulos, Mr. Apostolos', 'male', 26.0, 1, 0),
 (75, 'Bing, Mr. Lee', 'male', 32.0, 0, 0),
 (76, 'Moen, Mr. Sigurd Hansen', 'male', 25.0, 0, 0),
 (77, 'Staneff, Mr. Ivan', 'male', 0.0, 0, 0),
 (78, 'Moutal, Mr. Rahamin Haim', 'male', 0.0, 0, 0),
 (79, 'Caldwell, Master. Alden Gates', 'male', 0.83, 0, 2),
 (80, 'Dowdell, Miss. Elizabeth', 'female', 30.0, 0, 0),
 (81, 'Waelens, Mr. Achille', 'male', 22.0, 0, 0),
 (82, 'Sheerlinck, Mr. Jan Baptist', 'male', 29.0, 0, 0),
 (83, 'McDermott, Miss. Brigdet Delia', 'female', 0.0, 0, 0),
 (84, 'Carrau, Mr. Francisco M', 'male', 28.0, 0, 0),
 (85, 'Ilett, Miss. Bertha', 'female', 17.0, 0, 0),
 (86, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female', 33.0, 3, 0),
 (87, 'Ford, Mr. William Neal', 'male', 16.0, 1, 3),
 (88, 'Slocovski, Mr. Selman Francis', 'male', 0.0, 0, 0),
 (89, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 3, 2),
 (90, 'Celotti, Mr. Francesco', 'male', 24.0, 0, 0),
 (91, 'Christmann, Mr. Emil', 'male', 29.0, 0, 0),
 (92, 'Andreasson, Mr. Paul Edvin', 'male', 20.0, 0, 0),
 (93, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 1, 0),
 (94, 'Dean, Mr. Bertram Frank', 'male', 26.0, 1, 2),
 (95, 'Coxon, Mr. Daniel', 'male', 59.0, 0, 0),
 (96, 'Shorney, Mr. Charles Joseph', 'male', 0.0, 0, 0),
 (97, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0),
 (98, 'Greenfield, Mr. William Bertram', 'male', 23.0, 0, 1),
 (99, 'Doling, Mrs. John T (Ada Julia Bone)', 'female', 34.0, 0, 1),
 (100, 'Kantor, Mr. Sinai', 'male', 34.0, 1, 0),
 (101, 'Petranec, Miss. Matilda', 'female', 28.0, 0, 0),
 (102, 'Petroff, Mr. Pastcho ("Pentcho")', 'male', 0.0, 0, 0),
 (103, 'White, Mr. Richard Frasar', 'male', 21.0, 0, 1),
 (104, 'Johansson, Mr. Gustaf Joel', 'male', 33.0, 0, 0),
 (105, 'Gustafsson, Mr. Anders Vilhelm', 'male', 37.0, 2, 0),
 (106, 'Mionoff, Mr. Stoytcho', 'male', 28.0, 0, 0),
 (107, 'Salkjelsvik, Miss. Anna Kristine', 'female', 21.0, 0, 0),
 (108, 'Moss, Mr. Albert Johan', 'male', 0.0, 0, 0),
 (109, 'Rekic, Mr. Tido', 'male', 38.0, 0, 0),
 (110, 'Moran, Miss. Bertha', 'female', 0.0, 1, 0),
 (111, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 0, 0),
 (112, 'Zabour, Miss. Hileni', 'female', 14.5, 1, 0),
 (113, 'Barton, Mr. David John', 'male', 22.0, 0, 0),
 (114, 'Jussila, Miss. Katriina', 'female', 20.0, 1, 0),
 (115, 'Attalah, Miss. Malake', 'female', 17.0, 0, 0),
 (116, 'Pekoniemi, Mr. Edvard', 'male', 21.0, 0, 0),
 (117, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0),
 (118, 'Turpin, Mr. William John Robert', 'male', 29.0, 1, 0),
 (119, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 0, 1),
 (120, 'Andersson, Miss. Ellis Anna Maria', 'female', 2.0, 4, 2),
 (121, 'Hickman, Mr. Stanley George', 'male', 21.0, 2, 0),
 (122, 'Moore, Mr. Leonard Charles', 'male', 0.0, 0, 0),
 (123, 'Nasser, Mr. Nicholas', 'male', 32.5, 1, 0),
 (124, 'Webber, Miss. Susan', 'female', 32.5, 0, 0),
 (125, 'White, Mr. Percival Wayland', 'male', 54.0, 0, 1),
 (126, 'Nicola-Yarred, Master. Elias', 'male', 12.0, 1, 0),
 (127, 'McMahon, Mr. Martin', 'male', 0.0, 0, 0),
 (128, 'Madsen, Mr. Fridtjof Arne', 'male', 24.0, 0, 0),
 (129, 'Peter, Miss. Anna', 'female', 0.0, 1, 1),
 (130, 'Ekstrom, Mr. Johan', 'male', 45.0, 0, 0),
 (131, 'Drazenoic, Mr. Jozef', 'male', 33.0, 0, 0),
 (132, 'Coelho, Mr. Domingos Fernandeo', 'male', 20.0, 0, 0),
 (133, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female', 47.0, 1, 0),
 (134, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female', 29.0, 1, 0),
 (135, 'Sobey, Mr. Samuel James Hayden', 'male', 25.0, 0, 0),
 (136, 'Richard, Mr. Emile', 'male', 23.0, 0, 0),
 (137, 'Newsom, Miss. Helen Monypeny', 'female', 19.0, 0, 2),
 (138, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 1, 0),
 (139, 'Osen, Mr. Olaf Elon', 'male', 16.0, 0, 0),
 (140, 'Giglio, Mr. Victor', 'male', 24.0, 0, 0),
 (141, 'Boulos, Mrs. Joseph (Sultana)', 'female', 0.0, 0, 2),
 (142, 'Nysten, Miss. Anna Sofia', 'female', 22.0, 0, 0),
 (143, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'female', 24.0, 1, 0),
 (144, 'Burke, Mr. Jeremiah', 'male', 19.0, 0, 0),
 (145, 'Andrew, Mr. Edgardo Samuel', 'male', 18.0, 0, 0),
 (146, 'Nicholls, Mr. Joseph Charles', 'male', 19.0, 1, 1),
 (147, 'Andersson, Mr. August Edvard ("Wennerstrom")', 'male', 27.0, 0, 0),
 (148, 'Ford, Miss. Robina Maggie "Ruby"', 'female', 9.0, 2, 2),
 (149, 'Navratil, Mr. Michel ("Louis M Hoffman")', 'male', 36.5, 0, 2),
 (150, 'Byles, Rev. Thomas Roussel Davids', 'male', 42.0, 0, 0),
 (151, 'Bateman, Rev. Robert James', 'male', 51.0, 0, 0),
 (152, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 1, 0),
 (153, 'Meo, Mr. Alfonzo', 'male', 55.5, 0, 0),
 (154, 'van Billiard, Mr. Austin Blyler', 'male', 40.5, 0, 2),
 (155, 'Olsen, Mr. Ole Martin', 'male', 0.0, 0, 0),
 (156, 'Williams, Mr. Charles Duane', 'male', 51.0, 0, 1),
 (157, 'Gilnagh, Miss. Katherine "Katie"', 'female', 16.0, 0, 0),
 (158, 'Corn, Mr. Harry', 'male', 30.0, 0, 0),
 (159, 'Smiljanic, Mr. Mile', 'male', 0.0, 0, 0),
 (160, 'Sage, Master. Thomas Henry', 'male', 0.0, 8, 2),
 (161, 'Cribb, Mr. John Hatfield', 'male', 44.0, 0, 1),
 (162, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'female', 40.0, 0, 0),
 (163, 'Bengtsson, Mr. John Viktor', 'male', 26.0, 0, 0),
 (164, 'Calic, Mr. Jovo', 'male', 17.0, 0, 0),
 (165, 'Panula, Master. Eino Viljami', 'male', 1.0, 4, 1),
 (166, 'Goldsmith, Master. Frank John William "Frankie"', 'male', 9.0, 0, 2),
 (167, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', 0.0, 0, 1),
 (168, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'female', 45.0, 1, 4),
 (169, 'Baumann, Mr. John D', 'male', 0.0, 0, 0),
 (170, 'Ling, Mr. Lee', 'male', 28.0, 0, 0),
 (171, 'Van der hoef, Mr. Wyckoff', 'male', 61.0, 0, 0),
 (172, 'Rice, Master. Arthur', 'male', 4.0, 4, 1),
 (173, 'Johnson, Miss. Eleanor Ileen', 'female', 1.0, 1, 1),
 (174, 'Sivola, Mr. Antti Wilhelm', 'male', 21.0, 0, 0),
 (175, 'Smith, Mr. James Clinch', 'male', 56.0, 0, 0),
 (176, 'Klasen, Mr. Klas Albin', 'male', 18.0, 1, 1),
 (177, 'Lefebre, Master. Henry Forbes', 'male', 0.0, 3, 1),
 (178, 'Isham, Miss. Ann Elizabeth', 'female', 50.0, 0, 0),
 (179, 'Hale, Mr. Reginald', 'male', 30.0, 0, 0),
 (180, 'Leonard, Mr. Lionel', 'male', 36.0, 0, 0),
 (181, 'Sage, Miss. Constance Gladys', 'female', 0.0, 8, 2),
 (182, 'Pernot, Mr. Rene', 'male', 0.0, 0, 0),
 (183, 'Asplund, Master. Clarence Gustaf Hugo', 'male', 9.0, 4, 2),
 (184, 'Becker, Master. Richard F', 'male', 1.0, 2, 1),
 (185, 'Kink-Heilmann, Miss. Luise Gretchen', 'female', 4.0, 0, 2),
 (186, 'Rood, Mr. Hugh Roscoe', 'male', 0.0, 0, 0),
 (187, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 'female', 0.0, 1, 0),
 (188, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 0, 0),
 (189, 'Bourke, Mr. John', 'male', 40.0, 1, 1),
 (190, 'Turcin, Mr. Stjepan', 'male', 36.0, 0, 0),
 (191, 'Pinsky, Mrs. (Rosa)', 'female', 32.0, 0, 0),
 (192, 'Carbines, Mr. William', 'male', 19.0, 0, 0),
 (193, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 'female', 19.0, 1, 0),
 (194, 'Navratil, Master. Michel M', 'male', 3.0, 1, 1),
 (195, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', 44.0, 0, 0),
 (196, 'Lurette, Miss. Elise', 'female', 58.0, 0, 0),
 (197, 'Mernagh, Mr. Robert', 'male', 0.0, 0, 0),
 (198, 'Olsen, Mr. Karl Siegwart Andreas', 'male', 42.0, 0, 1),
 (199, 'Madigan, Miss. Margaret "Maggie"', 'female', 0.0, 0, 0),
 (200, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 'female', 24.0, 0, 0),
 (201, 'Vande Walle, Mr. Nestor Cyriel', 'male', 28.0, 0, 0),
 (202, 'Sage, Mr. Frederick', 'male', 0.0, 8, 2),
 (203, 'Johanson, Mr. Jakob Alfred', 'male', 34.0, 0, 0),
 (204, 'Youseff, Mr. Gerious', 'male', 45.5, 0, 0),
 (205, 'Cohen, Mr. Gurshon "Gus"', 'male', 18.0, 0, 0),
 (206, 'Strom, Miss. Telma Matilda', 'female', 2.0, 0, 1),
 (207, 'Backstrom, Mr. Karl Alfred', 'male', 32.0, 1, 0),
 (208, 'Albimona, Mr. Nassef Cassem', 'male', 26.0, 0, 0),
 (209, 'Carr, Miss. Helen "Ellen"', 'female', 16.0, 0, 0),
 (210, 'Blank, Mr. Henry', 'male', 40.0, 0, 0),
 (211, 'Ali, Mr. Ahmed', 'male', 24.0, 0, 0),
 (212, 'Cameron, Miss. Clear Annie', 'female', 35.0, 0, 0),
 (213, 'Perkin, Mr. John Henry', 'male', 22.0, 0, 0),
 (214, 'Givard, Mr. Hans Kristensen', 'male', 30.0, 0, 0),
 (215, 'Kiernan, Mr. Philip', 'male', 0.0, 1, 0),
 (216, 'Newell, Miss. Madeleine', 'female', 31.0, 1, 0),
 (217, 'Honkanen, Miss. Eliina', 'female', 27.0, 0, 0),
 (218, 'Jacobsohn, Mr. Sidney Samuel', 'male', 42.0, 1, 0),
 (219, 'Bazzani, Miss. Albina', 'female', 32.0, 0, 0),
 (220, 'Harris, Mr. Walter', 'male', 30.0, 0, 0),
 (221, 'Sunderland, Mr. Victor Francis', 'male', 16.0, 0, 0),
 (222, 'Bracken, Mr. James H', 'male', 27.0, 0, 0),
 (223, 'Green, Mr. George Henry', 'male', 51.0, 0, 0),
 (224, 'Nenkoff, Mr. Christo', 'male', 0.0, 0, 0),
 (225, 'Hoyt, Mr. Frederick Maxfield', 'male', 38.0, 1, 0),
 (226, 'Berglund, Mr. Karl Ivar Sven', 'male', 22.0, 0, 0),
 (227, 'Mellors, Mr. William John', 'male', 19.0, 0, 0),
 (228, 'Lovell, Mr. John Hall ("Henry")', 'male', 20.5, 0, 0),
 (229, 'Fahlstrom, Mr. Arne Jonas', 'male', 18.0, 0, 0),
 (230, 'Lefebre, Miss. Mathilde', 'female', 0.0, 3, 1),
 (231, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'female', 35.0, 1, 0),
 (232, 'Larsson, Mr. Bengt Edvin', 'male', 29.0, 0, 0),
 (233, 'Sjostedt, Mr. Ernst Adolf', 'male', 59.0, 0, 0),
 (234, 'Asplund, Miss. Lillian Gertrud', 'female', 5.0, 4, 2),
 (235, 'Leyson, Mr. Robert William Norman', 'male', 24.0, 0, 0),
 (236, 'Harknett, Miss. Alice Phoebe', 'female', 0.0, 0, 0),
 (237, 'Hold, Mr. Stephen', 'male', 44.0, 1, 0),
 (238, 'Collyer, Miss. Marjorie "Lottie"', 'female', 8.0, 0, 2),
 (239, 'Pengelly, Mr. Frederick William', 'male', 19.0, 0, 0),
 (240, 'Hunt, Mr. George Henry', 'male', 33.0, 0, 0),
 (241, 'Zabour, Miss. Thamine', 'female', 0.0, 1, 0),
 (242, 'Murphy, Miss. Katherine "Kate"', 'female', 0.0, 1, 0),
 (243, 'Coleridge, Mr. Reginald Charles', 'male', 29.0, 0, 0),
 (244, 'Maenpaa, Mr. Matti Alexanteri', 'male', 22.0, 0, 0),
 (245, 'Attalah, Mr. Sleiman', 'male', 30.0, 0, 0),
 (246, 'Minahan, Dr. William Edward', 'male', 44.0, 2, 0),
 (247, 'Lindahl, Miss. Agda Thorilda Viktoria', 'female', 25.0, 0, 0),
 (248, 'Hamalainen, Mrs. William (Anna)', 'female', 24.0, 0, 2),
 (249, 'Beckwith, Mr. Richard Leonard', 'male', 37.0, 1, 1),
 (250, 'Carter, Rev. Ernest Courtenay', 'male', 54.0, 1, 0),
 (251, 'Reed, Mr. James George', 'male', 0.0, 0, 0),
 (252, 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 'female', 29.0, 1, 1),
 (253, 'Stead, Mr. William Thomas', 'male', 62.0, 0, 0),
 (254, 'Lobb, Mr. William Arthur', 'male', 30.0, 1, 0),
 (255, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 'female', 41.0, 0, 2),
 (256, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 'female', 29.0, 0, 2),
 (257, 'Thorne, Mrs. Gertrude Maybelle', 'female', 0.0, 0, 0),
 (258, 'Cherry, Miss. Gladys', 'female', 30.0, 0, 0),
 (259, 'Ward, Miss. Anna', 'female', 35.0, 0, 0),
 (260, 'Parrish, Mrs. (Lutie Davis)', 'female', 50.0, 0, 1),
 (261, 'Smith, Mr. Thomas', 'male', 0.0, 0, 0),
 (262, 'Asplund, Master. Edvin Rojj Felix', 'male', 3.0, 4, 2),
 (263, 'Taussig, Mr. Emil', 'male', 52.0, 1, 1),
 (264, 'Harrison, Mr. William', 'male', 40.0, 0, 0),
 (265, 'Henry, Miss. Delia', 'female', 0.0, 0, 0),
 (266, 'Reeves, Mr. David', 'male', 36.0, 0, 0),
 (267, 'Panula, Mr. Ernesti Arvid', 'male', 16.0, 4, 1),
 (268, 'Persson, Mr. Ernst Ulrik', 'male', 25.0, 1, 0),
 (269, 'Graham, Mrs. William Thompson (Edith Junkins)', 'female', 58.0, 0, 1),
 (270, 'Bissette, Miss. Amelia', 'female', 35.0, 0, 0),
 (271, 'Cairns, Mr. Alexander', 'male', 0.0, 0, 0),
 (272, 'Tornquist, Mr. William Henry', 'male', 25.0, 0, 0),
 (273, 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 'female', 41.0, 0, 1),
 (274, 'Natsch, Mr. Charles H', 'male', 37.0, 0, 1),
 (275, 'Healy, Miss. Hanora "Nora"', 'female', 0.0, 0, 0),
 (276, 'Andrews, Miss. Kornelia Theodosia', 'female', 63.0, 1, 0),
 (277, 'Lindblom, Miss. Augusta Charlotta', 'female', 45.0, 0, 0),
 (278, 'Parkes, Mr. Francis "Frank"', 'male', 0.0, 0, 0),
 (279, 'Rice, Master. Eric', 'male', 7.0, 4, 1),
 (280, 'Abbott, Mrs. Stanton (Rosa Hunt)', 'female', 35.0, 1, 1),
 (281, 'Duane, Mr. Frank', 'male', 65.0, 0, 0),
 (282, 'Olsson, Mr. Nils Johan Goransson', 'male', 28.0, 0, 0),
 (283, 'de Pelsmaeker, Mr. Alfons', 'male', 16.0, 0, 0),
 (284, 'Dorking, Mr. Edward Arthur', 'male', 19.0, 0, 0),
 (285, 'Smith, Mr. Richard William', 'male', 0.0, 0, 0),
 (286, 'Stankovic, Mr. Ivan', 'male', 33.0, 0, 0),
 (287, 'de Mulder, Mr. Theodore', 'male', 30.0, 0, 0),
 (288, 'Naidenoff, Mr. Penko', 'male', 22.0, 0, 0),
 (289, 'Hosono, Mr. Masabumi', 'male', 42.0, 0, 0),
 (290, 'Connolly, Miss. Kate', 'female', 22.0, 0, 0),
 (291, 'Barber, Miss. Ellen "Nellie"', 'female', 26.0, 0, 0),
 (292, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', 19.0, 1, 0),
 (293, 'Levy, Mr. Rene Jacques', 'male', 36.0, 0, 0),
 (294, 'Haas, Miss. Aloisia', 'female', 24.0, 0, 0),
 (295, 'Mineff, Mr. Ivan', 'male', 24.0, 0, 0),
 (296, 'Lewy, Mr. Ervin G', 'male', 0.0, 0, 0),
 (297, 'Hanna, Mr. Mansour', 'male', 23.5, 0, 0),
 (298, 'Allison, Miss. Helen Loraine', 'female', 2.0, 1, 2),
 (299, 'Saalfeld, Mr. Adolphe', 'male', 0.0, 0, 0),
 (300, 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'female', 50.0, 0, 1),
 (301, 'Kelly, Miss. Anna Katherine "Annie Kate"', 'female', 0.0, 0, 0),
 (302, 'McCoy, Mr. Bernard', 'male', 0.0, 2, 0),
 (303, 'Johnson, Mr. William Cahoone Jr', 'male', 19.0, 0, 0),
 (304, 'Keane, Miss. Nora A', 'female', 0.0, 0, 0),
 (305, 'Williams, Mr. Howard Hugh "Harry"', 'male', 0.0, 0, 0),
 (306, 'Allison, Master. Hudson Trevor', 'male', 0.92, 1, 2),
 (307, 'Fleming, Miss. Margaret', 'female', 0.0, 0, 0),
 (308, 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 'female', 17.0, 1, 0),
 (309, 'Abelson, Mr. Samuel', 'male', 30.0, 1, 0),
 (310, 'Francatelli, Miss. Laura Mabel', 'female', 30.0, 0, 0),
 (311, 'Hays, Miss. Margaret Bechstein', 'female', 24.0, 0, 0),
 (312, 'Ryerson, Miss. Emily Borie', 'female', 18.0, 2, 2),
 (313, 'Lahtinen, Mrs. William (Anna Sylfven)', 'female', 26.0, 1, 1),
 (314, 'Hendekovic, Mr. Ignjac', 'male', 28.0, 0, 0),
 (315, 'Hart, Mr. Benjamin', 'male', 43.0, 1, 1),
 (316, 'Nilsson, Miss. Helmina Josefina', 'female', 26.0, 0, 0),
 (317, 'Kantor, Mrs. Sinai (Miriam Sternin)', 'female', 24.0, 1, 0),
 (318, 'Moraweck, Dr. Ernest', 'male', 54.0, 0, 0),
 (319, 'Wick, Miss. Mary Natalie', 'female', 31.0, 0, 2),
 (320, 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', 'female', 40.0, 1, 1),
 (321, 'Dennis, Mr. Samuel', 'male', 22.0, 0, 0),
 (322, 'Danoff, Mr. Yoto', 'male', 27.0, 0, 0),
 (323, 'Slayter, Miss. Hilda Mary', 'female', 30.0, 0, 0),
 (324, 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', 'female', 22.0, 1, 1),
 (325, 'Sage, Mr. George John Jr', 'male', 0.0, 8, 2),
 (326, 'Young, Miss. Marie Grice', 'female', 36.0, 0, 0),
 (327, 'Nysveen, Mr. Johan Hansen', 'male', 61.0, 0, 0),
 (328, 'Ball, Mrs. (Ada E Hall)', 'female', 36.0, 0, 0),
 (329, 'Goldsmith, Mrs. Frank John (Emily Alice Brown)', 'female', 31.0, 1, 1),
 (330, 'Hippach, Miss. Jean Gertrude', 'female', 16.0, 0, 1),
 (331, 'McCoy, Miss. Agnes', 'female', 0.0, 2, 0),
 (332, 'Partner, Mr. Austen', 'male', 45.5, 0, 0),
 (333, 'Graham, Mr. George Edward', 'male', 38.0, 0, 1),
 (334, 'Vander Planke, Mr. Leo Edmondus', 'male', 16.0, 2, 0),
 (335, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 'female', 0.0, 1, 0),
 (336, 'Denkoff, Mr. Mitto', 'male', 0.0, 0, 0),
 (337, 'Pears, Mr. Thomas Clinton', 'male', 29.0, 1, 0),

In [35]:
%%sql
select * from survivant;

 * postgresql://user1:***@localhost/postgres
891 rows affected.

[(1, 'Braund, Mr. Owen Harris', 0),
 (2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 1),
 (3, 'Heikkinen, Miss. Laina', 1),
 (4, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 1),
 (5, 'Allen, Mr. William Henry', 0),
 (6, 'Moran, Mr. James', 0),
 (7, 'McCarthy, Mr. Timothy J', 0),
 (8, 'Palsson, Master. Gosta Leonard', 0),
 (9, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 1),
 (10, 'Nasser, Mrs. Nicholas (Adele Achem)', 1),
 (11, 'Sandstrom, Miss. Marguerite Rut', 1),
 (12, 'Bonnell, Miss. Elizabeth', 1),
 (13, 'Saundercock, Mr. William Henry', 0),
 (14, 'Andersson, Mr. Anders Johan', 0),
 (15, 'Vestrom, Miss. Hulda Amanda Adolfina', 0),
 (16, 'Hewlett, Mrs. (Mary D Kingcome) ', 1),
 (17, 'Rice, Master. Eugene', 0),
 (18, 'Williams, Mr. Charles Eugene', 1),
 (19, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 0),
 (20, 'Masselmani, Mrs. Fatima', 1),
 (21, 'Fynney, Mr. Joseph J', 0),
 (22, 'Beesley, Mr. Lawrence', 1),
 (23, 'McGowan, Miss. Anna "Annie"', 1),
 (24, 'Sloper, Mr. William Thompson', 1),
 (25, 'Palsson, Miss. Torborg Danira', 0),
 (26, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 1),
 (27, 'Emir, Mr. Farred Chehab', 0),
 (28, 'Fortune, Mr. Charles Alexander', 0),
 (29, 'O\'Dwyer, Miss. Ellen "Nellie"', 1),
 (30, 'Todoroff, Mr. Lalio', 0),
 (31, 'Uruchurtu, Don. Manuel E', 0),
 (32, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 1),
 (33, 'Glynn, Miss. Mary Agatha', 1),
 (34, 'Wheadon, Mr. Edward H', 0),
 (35, 'Meyer, Mr. Edgar Joseph', 0),
 (36, 'Holverson, Mr. Alexander Oskar', 0),
 (37, 'Mamee, Mr. Hanna', 1),
 (38, 'Cann, Mr. Ernest Charles', 0),
 (39, 'Vander Planke, Miss. Augusta Maria', 0),
 (40, 'Nicola-Yarred, Miss. Jamila', 1),
 (41, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 0),
 (42, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 0),
 (43, 'Kraeff, Mr. Theodor', 0),
 (44, 'Laroche, Miss. Simonne Marie Anne Andree', 1),
 (45, 'Devaney, Miss. Margaret Delia', 1),
 (46, 'Rogers, Mr. William John', 0),
 (47, 'Lennon, Mr. Denis', 0),
 (48, "O'Driscoll, Miss. Bridget", 1),
 (49, 'Samaan, Mr. Youssef', 0),
 (50, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 0),
 (51, 'Panula, Master. Juha Niilo', 0),
 (52, 'Nosworthy, Mr. Richard Cater', 0),
 (53, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 1),
 (54, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 1),
 (55, 'Ostby, Mr. Engelhart Cornelius', 0),
 (56, 'Woolner, Mr. Hugh', 1),
 (57, 'Rugg, Miss. Emily', 1),
 (58, 'Novel, Mr. Mansouer', 0),
 (59, 'West, Miss. Constance Mirium', 1),
 (60, 'Goodwin, Master. William Frederick', 0),
 (61, 'Sirayanian, Mr. Orsen', 0),
 (62, 'Icard, Miss. Amelie', 1),
 (63, 'Harris, Mr. Henry Birkhardt', 0),
 (64, 'Skoog, Master. Harald', 0),
 (65, 'Stewart, Mr. Albert A', 0),
 (66, 'Moubarek, Master. Gerios', 1),
 (67, 'Nye, Mrs. (Elizabeth Ramell)', 1),
 (68, 'Crease, Mr. Ernest James', 0),
 (69, 'Andersson, Miss. Erna Alexandra', 1),
 (70, 'Kink, Mr. Vincenz', 0),
 (71, 'Jenkin, Mr. Stephen Curnow', 0),
 (72, 'Goodwin, Miss. Lillian Amy', 0),
 (73, 'Hood, Mr. Ambrose Jr', 0),
 (74, 'Chronopoulos, Mr. Apostolos', 0),
 (75, 'Bing, Mr. Lee', 1),
 (76, 'Moen, Mr. Sigurd Hansen', 0),
 (77, 'Staneff, Mr. Ivan', 0),
 (78, 'Moutal, Mr. Rahamin Haim', 0),
 (79, 'Caldwell, Master. Alden Gates', 1),
 (80, 'Dowdell, Miss. Elizabeth', 1),
 (81, 'Waelens, Mr. Achille', 0),
 (82, 'Sheerlinck, Mr. Jan Baptist', 1),
 (83, 'McDermott, Miss. Brigdet Delia', 1),
 (84, 'Carrau, Mr. Francisco M', 0),
 (85, 'Ilett, Miss. Bertha', 1),
 (86, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 1),
 (87, 'Ford, Mr. William Neal', 0),
 (88, 'Slocovski, Mr. Selman Francis', 0),
 (89, 'Fortune, Miss. Mabel Helen', 1),
 (90, 'Celotti, Mr. Francesco', 0),
 (91, 'Christmann, Mr. Emil', 0),
 (92, 'Andreasson, Mr. Paul Edvin', 0),
 (93, 'Chaffee, Mr. Herbert Fuller', 0),
 (94, 'Dean, Mr. Bertram Frank', 0),
 (95, 'Coxon, Mr. Daniel', 0),
 (96, 'Shorney, Mr. Charles Joseph', 0),
 (97, 'Goldschmidt, Mr. George B', 0),
 (98, 'Greenfield, Mr. William Bertram', 1),
 (99, 'Doling, Mrs. John T (Ada Julia Bone)', 1),
 (100, 'Kantor, Mr. Sinai', 0),
 (101, 'Petranec, Miss. Matilda', 0),
 (102, 'Petroff, Mr. Pastcho ("Pentcho")', 0),
 (103, 'White, Mr. Richard Frasar', 0),
 (104, 'Johansson, Mr. Gustaf Joel', 0),
 (105, 'Gustafsson, Mr. Anders Vilhelm', 0),
 (106, 'Mionoff, Mr. Stoytcho', 0),
 (107, 'Salkjelsvik, Miss. Anna Kristine', 1),
 (108, 'Moss, Mr. Albert Johan', 1),
 (109, 'Rekic, Mr. Tido', 0),
 (110, 'Moran, Miss. Bertha', 1),
 (111, 'Porter, Mr. Walter Chamberlain', 0),
 (112, 'Zabour, Miss. Hileni', 0),
 (113, 'Barton, Mr. David John', 0),
 (114, 'Jussila, Miss. Katriina', 0),
 (115, 'Attalah, Miss. Malake', 0),
 (116, 'Pekoniemi, Mr. Edvard', 0),
 (117, 'Connors, Mr. Patrick', 0),
 (118, 'Turpin, Mr. William John Robert', 0),
 (119, 'Baxter, Mr. Quigg Edmond', 0),
 (120, 'Andersson, Miss. Ellis Anna Maria', 0),
 (121, 'Hickman, Mr. Stanley George', 0),
 (122, 'Moore, Mr. Leonard Charles', 0),
 (123, 'Nasser, Mr. Nicholas', 0),
 (124, 'Webber, Miss. Susan', 1),
 (125, 'White, Mr. Percival Wayland', 0),
 (126, 'Nicola-Yarred, Master. Elias', 1),
 (127, 'McMahon, Mr. Martin', 0),
 (128, 'Madsen, Mr. Fridtjof Arne', 1),
 (129, 'Peter, Miss. Anna', 1),
 (130, 'Ekstrom, Mr. Johan', 0),
 (131, 'Drazenoic, Mr. Jozef', 0),
 (132, 'Coelho, Mr. Domingos Fernandeo', 0),
 (133, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 0),
 (134, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 1),
 (135, 'Sobey, Mr. Samuel James Hayden', 0),
 (136, 'Richard, Mr. Emile', 0),
 (137, 'Newsom, Miss. Helen Monypeny', 1),
 (138, 'Futrelle, Mr. Jacques Heath', 0),
 (139, 'Osen, Mr. Olaf Elon', 0),
 (140, 'Giglio, Mr. Victor', 0),
 (141, 'Boulos, Mrs. Joseph (Sultana)', 0),
 (142, 'Nysten, Miss. Anna Sofia', 1),
 (143, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 1),
 (144, 'Burke, Mr. Jeremiah', 0),
 (145, 'Andrew, Mr. Edgardo Samuel', 0),
 (146, 'Nicholls, Mr. Joseph Charles', 0),
 (147, 'Andersson, Mr. August Edvard ("Wennerstrom")', 1),
 (148, 'Ford, Miss. Robina Maggie "Ruby"', 0),
 (149, 'Navratil, Mr. Michel ("Louis M Hoffman")', 0),
 (150, 'Byles, Rev. Thomas Roussel Davids', 0),
 (151, 'Bateman, Rev. Robert James', 0),
 (152, 'Pears, Mrs. Thomas (Edith Wearne)', 1),
 (153, 'Meo, Mr. Alfonzo', 0),
 (154, 'van Billiard, Mr. Austin Blyler', 0),
 (155, 'Olsen, Mr. Ole Martin', 0),
 (156, 'Williams, Mr. Charles Duane', 0),
 (157, 'Gilnagh, Miss. Katherine "Katie"', 1),
 (158, 'Corn, Mr. Harry', 0),
 (159, 'Smiljanic, Mr. Mile', 0),
 (160, 'Sage, Master. Thomas Henry', 0),
 (161, 'Cribb, Mr. John Hatfield', 0),
 (162, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 1),
 (163, 'Bengtsson, Mr. John Viktor', 0),
 (164, 'Calic, Mr. Jovo', 0),
 (165, 'Panula, Master. Eino Viljami', 0),
 (166, 'Goldsmith, Master. Frank John William "Frankie"', 1),
 (167, 'Chibnall, Mrs. (Edith Martha Bowerman)', 1),
 (168, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 0),
 (169, 'Baumann, Mr. John D', 0),
 (170, 'Ling, Mr. Lee', 0),
 (171, 'Van der hoef, Mr. Wyckoff', 0),
 (172, 'Rice, Master. Arthur', 0),
 (173, 'Johnson, Miss. Eleanor Ileen', 1),
 (174, 'Sivola, Mr. Antti Wilhelm', 0),
 (175, 'Smith, Mr. James Clinch', 0),
 (176, 'Klasen, Mr. Klas Albin', 0),
 (177, 'Lefebre, Master. Henry Forbes', 0),
 (178, 'Isham, Miss. Ann Elizabeth', 0),
 (179, 'Hale, Mr. Reginald', 0),
 (180, 'Leonard, Mr. Lionel', 0),
 (181, 'Sage, Miss. Constance Gladys', 0),
 (182, 'Pernot, Mr. Rene', 0),
 (183, 'Asplund, Master. Clarence Gustaf Hugo', 0),
 (184, 'Becker, Master. Richard F', 1),
 (185, 'Kink-Heilmann, Miss. Luise Gretchen', 1),
 (186, 'Rood, Mr. Hugh Roscoe', 0),
 (187, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 1),
 (188, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 1),
 (189, 'Bourke, Mr. John', 0),
 (190, 'Turcin, Mr. Stjepan', 0),
 (191, 'Pinsky, Mrs. (Rosa)', 1),
 (192, 'Carbines, Mr. William', 0),
 (193, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 1),
 (194, 'Navratil, Master. Michel M', 1),
 (195, 'Brown, Mrs. James Joseph (Margaret Tobin)', 1),
 (196, 'Lurette, Miss. Elise', 1),
 (197, 'Mernagh, Mr. Robert', 0),
 (198, 'Olsen, Mr. Karl Siegwart Andreas', 0),
 (199, 'Madigan, Miss. Margaret "Maggie"', 1),
 (200, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 0),
 (201, 'Vande Walle, Mr. Nestor Cyriel', 0),
 (202, 'Sage, Mr. Frederick', 0),
 (203, 'Johanson, Mr. Jakob Alfred', 0),
 (204, 'Youseff, Mr. Gerious', 0),
 (205, 'Cohen, Mr. Gurshon "Gus"', 1),
 (206, 'Strom, Miss. Telma Matilda', 0),
 (207, 'Backstrom, Mr. Karl Alfred', 0),
 (208, 'Albimona, Mr. Nassef Cassem', 1),
 (209, 'Carr, Miss. Helen "Ellen"', 1),
 (210, 'Blank, Mr. Henry', 1),
 (211, 'Ali, Mr. Ahmed', 0),
 (212, 'Cameron, Miss. Clear Annie', 1),
 (213, 'Perkin, Mr. John Henry', 0),
 (214, 'Givard, Mr. Hans Kristensen', 0),
 (215, 'Kiernan, Mr. Philip', 0),
 (216, 'Newell, Miss. Madeleine', 1),
 (217, 'Honkanen, Miss. Eliina', 1),
 (218, 'Jacobsohn, Mr. Sidney Samuel', 0),
 (219, 'Bazzani, Miss. Albina', 1),
 (220, 'Harris, Mr. Walter', 0),
 (221, 'Sunderland, Mr. Victor Francis', 1),
 (222, 'Bracken, Mr. James H', 0),
 (223, 'Green, Mr. George Henry', 0),
 (224, 'Nenkoff, Mr. Christo', 0),
 (225, 'Hoyt, Mr. Frederick Maxfield', 1),
 (226, 'Berglund, Mr. Karl Ivar Sven', 0),
 (227, 'Mellors, Mr. William John', 1),
 (228, 'Lovell, Mr. John Hall ("Henry")', 0),
 (229, 'Fahlstrom, Mr. Arne Jonas', 0),
 (230, 'Lefebre, Miss. Mathilde', 0),
 (231, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 1),
 (232, 'Larsson, Mr. Bengt Edvin', 0),
 (233, 'Sjostedt, Mr. Ernst Adolf', 0),
 (234, 'Asplund, Miss. Lillian Gertrud', 1),
 (235, 'Leyson, Mr. Robert William Norman', 0),
 (236, 'Harknett, Miss. Alice Phoebe', 0),
 (237, 'Hold, Mr. Stephen', 0),
 (238, 'Collyer, Miss. Marjorie "Lottie"', 1),
 (239, 'Pengelly, Mr. Frederick William', 0),
 (240, 'Hunt, Mr. George Henry', 0),
 (241, 'Zabour, Miss. Thamine', 0),
 (242, 'Murphy, Miss. Katherine "Kate"', 1),
 (243, 'Coleridge, Mr. Reginald Charles', 0),
 (244, 'Maenpaa, Mr. Matti Alexanteri', 0),
 (245, 'Attalah, Mr. Sleiman', 0),
 (246, 'Minahan, Dr. William Edward', 0),
 (247, 'Lindahl, Miss. Agda Thorilda Viktoria', 0),
 (248, 'Hamalainen, Mrs. William (Anna)', 1),
 (249, 'Beckwith, Mr. Richard Leonard', 1),
 (250, 'Carter, Rev. Ernest Courtenay', 0),
 (251, 'Reed, Mr. James George', 0),
 (252, 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 0),
 (253, 'Stead, Mr. William Thomas', 0),
 (254, 'Lobb, Mr. William Arthur', 0),
 (255, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 0),
 (256, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 1),
 (257, 'Thorne, Mrs. Gertrude Maybelle', 1),
 (258, 'Cherry, Miss. Gladys', 1),
 (259, 'Ward, Miss. Anna', 1),
 (260, 'Parrish, Mrs. (Lutie Davis)', 1),
 (261, 'Smith, Mr. Thomas', 0),
 (262, 'Asplund, Master. Edvin Rojj Felix', 1),
 (263, 'Taussig, Mr. Emil', 0),
 (264, 'Harrison, Mr. William', 0),
 (265, 'Henry, Miss. Delia', 0),
 (266, 'Reeves, Mr. David', 0),
 (267, 'Panula, Mr. Ernesti Arvid', 0),
 (268, 'Persson, Mr. Ernst Ulrik', 1),
 (269, 'Graham, Mrs. William Thompson (Edith Junkins)', 1),
 (270, 'Bissette, Miss. Amelia', 1),
 (271, 'Cairns, Mr. Alexander', 0),
 (272, 'Tornquist, Mr. William Henry', 1),
 (273, 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 1),
 (274, 'Natsch, Mr. Charles H', 0),
 (275, 'Healy, Miss. Hanora "Nora"', 1),
 (276, 'Andrews, Miss. Kornelia Theodosia', 1),
 (277, 'Lindblom, Miss. Augusta Charlotta', 0),
 (278, 'Parkes, Mr. Francis "Frank"', 0),
 (279, 'Rice, Master. Eric', 0),
 (280, 'Abbott, Mrs. Stanton (Rosa Hunt)', 1),
 (281, 'Duane, Mr. Frank', 0),
 (282, 'Olsson, Mr. Nils Johan Goransson', 0),
 (283, 'de Pelsmaeker, Mr. Alfons', 0),
 (284, 'Dorking, Mr. Edward Arthur', 1),
 (285, 'Smith, Mr. Richard William', 0),
 (286, 'Stankovic, Mr. Ivan', 0),
 (287, 'de Mulder, Mr. Theodore', 1),
 (288, 'Naidenoff, Mr. Penko', 0),
 (289, 'Hosono, Mr. Masabumi', 1),
 (290, 'Connolly, Miss. Kate', 1),
 (291, 'Barber, Miss. Ellen "Nellie"', 1),
 (292, 'Bishop, Mrs. Dickinson H (Helen Walton)', 1),
 (293, 'Levy, Mr. Rene Jacques', 0),
 (294, 'Haas, Miss. Aloisia', 0),
 (295, 'Mineff, Mr. Ivan', 0),
 (296, 'Lewy, Mr. Ervin G', 0),
 (297, 'Hanna, Mr. Mansour', 0),
 (298, 'Allison, Miss. Helen Loraine', 0),
 (299, 'Saalfeld, Mr. Adolphe', 1),
 (300, 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 1),
 (301, 'Kelly, Miss. Anna Katherine "Annie Kate"', 1),
 (302, 'McCoy, Mr. Bernard', 1),
 (303, 'Johnson, Mr. William Cahoone Jr', 0),
 (304, 'Keane, Miss. Nora A', 1),
 (305, 'Williams, Mr. Howard Hugh "Harry"', 0),
 (306, 'Allison, Master. Hudson Trevor', 1),
 (307, 'Fleming, Miss. Margaret', 1),
 (308, 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 1),
 (309, 'Abelson, Mr. Samuel', 0),
 (310, 'Francatelli, Miss. Laura Mabel', 1),
 (311, 'Hays, Miss. Margaret Bechstein', 1),
 (312, 'Ryerson, Miss. Emily Borie', 1),
 (313, 'Lahtinen, Mrs. William (Anna Sylfven)', 0),
 (314, 'Hendekovic, Mr. Ignjac', 0),
 (315, 'Hart, Mr. Benjamin', 0),
 (316, 'Nilsson, Miss. Helmina Josefina', 1),
 (317, 'Kantor, Mrs. Sinai (Miriam Sternin)', 1),
 (318, 'Moraweck, Dr. Ernest', 0),
 (319, 'Wick, Miss. Mary Natalie', 1),
 (320, 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', 1),
 (321, 'Dennis, Mr. Samuel', 0),
 (322, 'Danoff, Mr. Yoto', 0),
 (323, 'Slayter, Miss. Hilda Mary', 1),
 (324, 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', 1),
 (325, 'Sage, Mr. George John Jr', 0),
 (326, 'Young, Miss. Marie Grice', 1),
 (327, 'Nysveen, Mr. Johan Hansen', 0),
 (328, 'Ball, Mrs. (Ada E Hall)', 1),
 (329, 'Goldsmith, Mrs. Frank John (Emily Alice Brown)', 1),
 (330, 'Hippach, Miss. Jean Gertrude', 1),
 (331, 'McCoy, Miss. Agnes', 1),
 (332, 'Partner, Mr. Austen', 0),
 (333, 'Graham, Mr. George Edward', 0),
 (334, 'Vander Planke, Mr. Leo Edmondus', 0),
 (335, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 1),
 (336, 'Denkoff, Mr. Mitto', 0),
 (337, 'Pears, Mr. Thomas Clinton', 0),
 (338, 'Burns, Miss. Elizabeth Margaret', 1),
 (339, 'Dahl, Mr. Karl Edwart', 1),
 (340, 'Blackwell, Mr. Stephen Weart', 0),
 (341, 'Navratil, Master. Edmond Roger', 1),
 (342, 'Fortune, Miss. Alice Elizabeth', 1),
 (343, 'Collander, Mr. Erik Gustaf', 0),
 (344, 'Sedgwick, Mr. Charles Frederick Waddington', 0),
 (345, 'Fox, Mr. Stanley Hubert', 0),
 (346, 'Brown, Miss. Amelia "Mildred"', 1),
 (347, 'Smith, Miss. Marion Elsie', 1),
 (348, 'Davison, Mrs. Thomas Henry (Mary E Finck)', 1),
 (349, 'Coutts, Master. William Loch "William"', 1),
 (350, 'Dimic, Mr. Jovan', 0),
 (351, 'Odahl, Mr. Nils Martin', 0),
 (352, 'Williams-Lambert, Mr. Fletcher Fellows', 0),
 (353, 'Elias, Mr. Tannous', 0),
 (354, 'Arnold-Franchi, Mr. Josef', 0),
 (355, 'Yousif, Mr. Wazli', 0),
 (356, 'Vanden Steen, Mr. Leo Peter', 0),
 (357, 'Bowerman, Miss. Elsie Edith', 1),
 (358, 'Funk, Miss. Annie Clemmer', 0),
 (359, 'McGovern, Miss. Mary', 1),
 (360, 'Mockler, Miss. Helen Mary "Ellie"', 1),
 (361, 'Skoog, Mr. Wilhelm', 0),
 (362, 'del Carlo, Mr. Sebastiano', 0),
 (363, 'Barbara, Mrs. (Catherine David)', 0),
 (364, 'Asim, Mr. Adola', 0),
 (365, "O'Brien, Mr. Thomas", 0),
 (366, 'Adahl, Mr. Mauritz Nils Martin', 0),
 (367, 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)', 1),
 (368, 'Moussa, Mrs. (Mantoura Boulos)', 1),
 (369, 'Jermyn, Miss. Annie', 1),
 (370, 'Aubart, Mme. Leontine Pauline', 1),
 (371, 'Harder, Mr. George Achilles', 1),
 (372, 'Wiklund, Mr. Jakob Alfred', 0),
 (373, 'Beavan, Mr. William Thomas', 0),
 (374, 'Ringhini, Mr. Sante', 0),
 (375, 'Palsson, Miss. Stina Viola', 0),
 (376, 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 1),
 (377, 'Landergren, Miss. Aurora Adelia', 1),
 (378, 'Widener, Mr. Harry Elkins', 0),
 (379, 'Betros, Mr. Tannous', 0),
 (380, 'Gustafsson, Mr. Karl Gideon', 0),
 (381, 'Bidois, Miss. Rosalie', 1),
 (382, 'Nakid, Miss. Maria ("Mary")', 1),
 (383, 'Tikkanen, Mr. Juho', 0),
 (384, 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)', 1),
 (385, 'Plotcharsky, Mr. Vasil', 0),
 (386, 'Davies, Mr. Charles Henry', 0),
 (387, 'Goodwin, Master. Sidney Leonard', 0),
 (388, 'Buss, Miss. Kate', 1),
 (389, 'Sadlier, Mr. Matthew', 0),
 (390, 'Lehmann, Miss. Bertha', 1),
 (391, 'Carter, Mr. William Ernest', 1),
 (392, 'Jansson, Mr. Carl Olof', 1),
 (393, 'Gustafsson, Mr. Johan Birger', 0),
 (394, 'Newell, Miss. Marjorie', 1),
 (395, 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)', 1),
 (396, 'Johansson, Mr. Erik', 0),
 (397, 'Olsson, Miss. Elina', 0),
 (398, 'McKane, Mr. Peter David', 0),
 (399, 'Pain, Dr. Alfred', 0),
 (400, 'Trout, Mrs. William H (Jessie L)', 1),
 (401, 'Niskanen, Mr. Juha', 1),
 (402, 'Adams, Mr. John', 0),
 (403, 'Jussila, Miss. Mari Aina', 0),
 (404, 'Hakkarainen, Mr. Pekka Pietari', 0),
 (405, 'Oreskovic, Miss. Marija', 0),
 (406, 'Gale, Mr. Shadrach', 0),
 (407, 'Widegren, Mr. Carl/Charles Peter', 0),
 (408, 'Richards, Master. William Rowe', 1),
 (409, 'Birkeland, Mr. Hans Martin Monsen', 0),
 (410, 'Lefebre, Miss. Ida', 0),
 (411, 'Sdycoff, Mr. Todor', 0),
 (412, 'Hart, Mr. Henry', 0),
 (413, 'Minahan, Miss. Daisy E', 1),
 (414, 'Cunningham, Mr. Alfred Fleming', 0),
 (415, 'Sundman, Mr. Johan Julian', 1),
 (416, 'Meek, Mrs. Thomas (Annie Louise Rowley)', 0),
 (417, 'Drew, Mrs. James Vivian (Lulu Thorne Christian)', 1),
 (418, 'Silven, Miss. Lyyli Karoliina', 1),
 (419, 'Matthews, Mr. William John', 0),
 (420, 'Van Impe, Miss. Catharina', 0),
 (421, 'Gheorgheff, Mr. Stanio', 0),
 (422, 'Charters, Mr. David', 0),
 (423, 'Zimmerman, Mr. Leo', 0),
 (424, 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)', 0),
 (425, 'Rosblom, Mr. Viktor Richard', 0),
 (426, 'Wiseman, Mr. Phillippe', 0),
 (427, 'Clarke, Mrs. Charles V (Ada Maria Winfield)', 1),
 (428, 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")', 1),
 (429, 'Flynn, Mr. James', 0),
 (430, 'Pickard, Mr. Berk (Berk Trembisky)', 1),
 (431, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 1),
 (432, 'Thorneycroft, Mrs. Percival (Florence Kate White)', 1),
 (433, 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)', 1),
 (434, 'Kallio, Mr. Nikolai Erland', 0),
 (435, 'Silvey, Mr. William Baird', 0),
 (436, 'Carter, Miss. Lucile Polk', 1),
 (437, 'Ford, Miss. Doolina Margaret "Daisy"', 0),
 (438, 'Richards, Mrs. Sidney (Emily Hocking)', 1),
 (439, 'Fortune, Mr. Mark', 0),
 (440, 'Kvillner, Mr. Johan Henrik Johannesson', 0),
 (441, 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 1),
 (442, 'Hampe, Mr. Leon', 0),
 (443, 'Petterson, Mr. Johan Emil', 0),
 (444, 'Reynaldo, Ms. Encarnacion', 1),
 (445, 'Johannesen-Bratthammer, Mr. Bernt', 1),
 (446, 'Dodge, Master. Washington', 1),
 (447, 'Mellinger, Miss. Madeleine Violet', 1),
 (448, 'Seward, Mr. Frederic Kimber', 1),
 (449, 'Baclini, Miss. Marie Catherine', 1),
 (450, 'Peuchen, Major. Arthur Godfrey', 1),
 (451, 'West, Mr. Edwy Arthur', 0),
 (452, 'Hagland, Mr. Ingvald Olai Olsen', 0),
 (453, 'Foreman, Mr. Benjamin Laventall', 0),
 (454, 'Goldenberg, Mr. Samuel L', 1),
 (455, 'Peduzzi, Mr. Joseph', 0),
 (456, 'Jalsevac, Mr. Ivan', 1),
 (457, 'Millet, Mr. Francis Davis', 0),
 (458, 'Kenyon, Mrs. Frederick R (Marion)', 1),
 (459, 'Toomey, Miss. Ellen', 1),
 (460, "O'Connor, Mr. Maurice", 0),
 (461, 'Anderson, Mr. Harry', 1),
 (462, 'Morley, Mr. William', 0),
 (463, 'Gee, Mr. Arthur H', 0),
 (464, 'Milling, Mr. Jacob Christian', 0),
 (465, 'Maisner, Mr. Simon', 0),
 (466, 'Goncalves, Mr. Manuel Estanslas', 0),
 (467, 'Campbell, Mr. William', 0),
 (468, 'Smart, Mr. John Montgomery', 0),
 (469, 'Scanlan, Mr. James', 0),
 (470, 'Baclini, Miss. Helene Barbara', 1),
 (471, 'Keefe, Mr. Arthur', 0),
 (472, 'Cacic, Mr. Luka', 0),
 (473, 'West, Mrs. Edwy Arthur (Ada Mary Worth)', 1),
 (474, 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)', 1),
 (475, 'Strandberg, Miss. Ida Sofia', 0),
 (476, 'Clifford, Mr. George Quincy', 0),
 (477, 'Renouf, Mr. Peter Henry', 0),

In [36]:
%%sql
SELECT * from passager natural join survivant natural join ticket;

 * postgresql://user1:***@localhost/postgres
891 rows affected.

[('Braund, Mr. Owen Harris', 1, 'male', 22.0, 1, 0, 0, 3, 'A/5 21171', 7.25, '', 'S'),
 ('Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 2, 'female', 38.0, 1, 0, 1, 1, 'PC 17599', 71.2833, 'C85', 'C'),
 ('Heikkinen, Miss. Laina', 3, 'female', 26.0, 0, 0, 1, 3, 'STON/O2. 3101282', 7.925, '', 'S'),
 ('Futrelle, Mrs. Jacques Heath (Lily May Peel)', 4, 'female', 35.0, 1, 0, 1, 1, '113803', 53.1, 'C123', 'S'),
 ('Allen, Mr. William Henry', 5, 'male', 35.0, 0, 0, 0, 3, '373450', 8.05, '', 'S'),
 ('Moran, Mr. James', 6, 'male', 0.0, 0, 0, 0, 3, '330877', 8.4583, '', 'Q'),
 ('McCarthy, Mr. Timothy J', 7, 'male', 54.0, 0, 0, 0, 1, '17463', 51.8625, 'E46', 'S'),
 ('Palsson, Master. Gosta Leonard', 8, 'male', 2.0, 3, 1, 0, 3, '349909', 21.075, '', 'S'),
 ('Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 9, 'female', 27.0, 0, 2, 1, 3, '347742', 11.1333, '', 'S'),
 ('Nasser, Mrs. Nicholas (Adele Achem)', 10, 'female', 14.0, 1, 0, 1, 2, '237736', 30.0708, '', 'C'),
 ('Sandstrom, Miss. Marguerite Rut', 11, 'female', 4.0, 1, 1, 1, 3, 'PP 9549', 16.7, 'G6', 'S'),
 ('Bonnell, Miss. Elizabeth', 12, 'female', 58.0, 0, 0, 1, 1, '113783', 26.55, 'C103', 'S'),
 ('Saundercock, Mr. William Henry', 13, 'male', 20.0, 0, 0, 0, 3, 'A/5. 2151', 8.05, '', 'S'),
 ('Andersson, Mr. Anders Johan', 14, 'male', 39.0, 1, 5, 0, 3, '347082', 31.275, '', 'S'),
 ('Vestrom, Miss. Hulda Amanda Adolfina', 15, 'female', 14.0, 0, 0, 0, 3, '350406', 7.8542, '', 'S'),
 ('Hewlett, Mrs. (Mary D Kingcome) ', 16, 'female', 55.0, 0, 0, 1, 2, '248706', 16.0, '', 'S'),
 ('Rice, Master. Eugene', 17, 'male', 2.0, 4, 1, 0, 3, '382652', 29.125, '', 'Q'),
 ('Williams, Mr. Charles Eugene', 18, 'male', 0.0, 0, 0, 1, 2, '244373', 13.0, '', 'S'),
 ('Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 19, 'female', 31.0, 1, 0, 0, 3, '345763', 18.0, '', 'S'),
 ('Masselmani, Mrs. Fatima', 20, 'female', 0.0, 0, 0, 1, 3, '2649', 7.225, '', 'C'),
 ('Fynney, Mr. Joseph J', 21, 'male', 35.0, 0, 0, 0, 2, '239865', 26.0, '', 'S'),
 ('Beesley, Mr. Lawrence', 22, 'male', 34.0, 0, 0, 1, 2, '248698', 13.0, 'D56', 'S'),
 ('McGowan, Miss. Anna "Annie"', 23, 'female', 15.0, 0, 0, 1, 3, '330923', 8.0292, '', 'Q'),
 ('Sloper, Mr. William Thompson', 24, 'male', 28.0, 0, 0, 1, 1, '113788', 35.5, 'A6', 'S'),
 ('Palsson, Miss. Torborg Danira', 25, 'female', 8.0, 3, 1, 0, 3, '349909', 21.075, '', 'S'),
 ('Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 26, 'female', 38.0, 1, 5, 1, 3, '347077', 31.3875, '', 'S'),
 ('Emir, Mr. Farred Chehab', 27, 'male', 0.0, 0, 0, 0, 3, '2631', 7.225, '', 'C'),
 ('Fortune, Mr. Charles Alexander', 28, 'male', 19.0, 3, 2, 0, 1, '19950', 263.0, 'C23 C25 C27', 'S'),
 ('O\'Dwyer, Miss. Ellen "Nellie"', 29, 'female', 0.0, 0, 0, 1, 3, '330959', 7.8792, '', 'Q'),
 ('Todoroff, Mr. Lalio', 30, 'male', 0.0, 0, 0, 0, 3, '349216', 7.8958, '', 'S'),
 ('Uruchurtu, Don. Manuel E', 31, 'male', 40.0, 0, 0, 0, 1, 'PC 17601', 27.7208, '', 'C'),
 ('Spencer, Mrs. William Augustus (Marie Eugenie)', 32, 'female', 0.0, 1, 0, 1, 1, 'PC 17569', 146.5208, 'B78', 'C'),
 ('Glynn, Miss. Mary Agatha', 33, 'female', 0.0, 0, 0, 1, 3, '335677', 7.75, '', 'Q'),
 ('Wheadon, Mr. Edward H', 34, 'male', 66.0, 0, 0, 0, 2, 'C.A. 24579', 10.5, '', 'S'),
 ('Meyer, Mr. Edgar Joseph', 35, 'male', 28.0, 1, 0, 0, 1, 'PC 17604', 82.1708, '', 'C'),
 ('Holverson, Mr. Alexander Oskar', 36, 'male', 42.0, 1, 0, 0, 1, '113789', 52.0, '', 'S'),
 ('Mamee, Mr. Hanna', 37, 'male', 0.0, 0, 0, 1, 3, '2677', 7.2292, '', 'C'),
 ('Cann, Mr. Ernest Charles', 38, 'male', 21.0, 0, 0, 0, 3, 'A./5. 2152', 8.05, '', 'S'),
 ('Vander Planke, Miss. Augusta Maria', 39, 'female', 18.0, 2, 0, 0, 3, '345764', 18.0, '', 'S'),
 ('Nicola-Yarred, Miss. Jamila', 40, 'female', 14.0, 1, 0, 1, 3, '2651', 11.2417, '', 'C'),
 ('Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 41, 'female', 40.0, 1, 0, 0, 3, '7546', 9.475, '', 'S'),
 ('Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 42, 'female', 27.0, 1, 0, 0, 2, '11668', 21.0, '', 'S'),
 ('Kraeff, Mr. Theodor', 43, 'male', 0.0, 0, 0, 0, 3, '349253', 7.8958, '', 'C'),
 ('Laroche, Miss. Simonne Marie Anne Andree', 44, 'female', 3.0, 1, 2, 1, 2, 'SC/Paris 2123', 41.5792, '', 'C'),
 ('Devaney, Miss. Margaret Delia', 45, 'female', 19.0, 0, 0, 1, 3, '330958', 7.8792, '', 'Q'),
 ('Rogers, Mr. William John', 46, 'male', 0.0, 0, 0, 0, 3, 'S.C./A.4. 23567', 8.05, '', 'S'),
 ('Lennon, Mr. Denis', 47, 'male', 0.0, 1, 0, 0, 3, '370371', 15.5, '', 'Q'),
 ("O'Driscoll, Miss. Bridget", 48, 'female', 0.0, 0, 0, 1, 3, '14311', 7.75, '', 'Q'),
 ('Samaan, Mr. Youssef', 49, 'male', 0.0, 2, 0, 0, 3, '2662', 21.6792, '', 'C'),
 ('Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 50, 'female', 18.0, 1, 0, 0, 3, '349237', 17.8, '', 'S'),
 ('Panula, Master. Juha Niilo', 51, 'male', 7.0, 4, 1, 0, 3, '3101295', 39.6875, '', 'S'),
 ('Nosworthy, Mr. Richard Cater', 52, 'male', 21.0, 0, 0, 0, 3, 'A/4. 39886', 7.8, '', 'S'),
 ('Harper, Mrs. Henry Sleeper (Myna Haxtun)', 53, 'female', 49.0, 1, 0, 1, 1, 'PC 17572', 76.7292, 'D33', 'C'),
 ('Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 54, 'female', 29.0, 1, 0, 1, 2, '2926', 26.0, '', 'S'),
 ('Ostby, Mr. Engelhart Cornelius', 55, 'male', 65.0, 0, 1, 0, 1, '113509', 61.9792, 'B30', 'C'),
 ('Woolner, Mr. Hugh', 56, 'male', 0.0, 0, 0, 1, 1, '19947', 35.5, 'C52', 'S'),
 ('Rugg, Miss. Emily', 57, 'female', 21.0, 0, 0, 1, 2, 'C.A. 31026', 10.5, '', 'S'),
 ('Novel, Mr. Mansouer', 58, 'male', 28.5, 0, 0, 0, 3, '2697', 7.2292, '', 'C'),
 ('West, Miss. Constance Mirium', 59, 'female', 5.0, 1, 2, 1, 2, 'C.A. 34651', 27.75, '', 'S'),
 ('Goodwin, Master. William Frederick', 60, 'male', 11.0, 5, 2, 0, 3, 'CA 2144', 46.9, '', 'S'),
 ('Sirayanian, Mr. Orsen', 61, 'male', 22.0, 0, 0, 0, 3, '2669', 7.2292, '', 'C'),
 ('Icard, Miss. Amelie', 62, 'female', 38.0, 0, 0, 1, 1, '113572', 80.0, 'B28', ''),
 ('Harris, Mr. Henry Birkhardt', 63, 'male', 45.0, 1, 0, 0, 1, '36973', 83.475, 'C83', 'S'),
 ('Skoog, Master. Harald', 64, 'male', 4.0, 3, 2, 0, 3, '347088', 27.9, '', 'S'),
 ('Stewart, Mr. Albert A', 65, 'male', 0.0, 0, 0, 0, 1, 'PC 17605', 27.7208, '', 'C'),
 ('Moubarek, Master. Gerios', 66, 'male', 0.0, 1, 1, 1, 3, '2661', 15.2458, '', 'C'),
 ('Nye, Mrs. (Elizabeth Ramell)', 67, 'female', 29.0, 0, 0, 1, 2, 'C.A. 29395', 10.5, 'F33', 'S'),
 ('Crease, Mr. Ernest James', 68, 'male', 19.0, 0, 0, 0, 3, 'S.P. 3464', 8.1583, '', 'S'),
 ('Andersson, Miss. Erna Alexandra', 69, 'female', 17.0, 4, 2, 1, 3, '3101281', 7.925, '', 'S'),
 ('Kink, Mr. Vincenz', 70, 'male', 26.0, 2, 0, 0, 3, '315151', 8.6625, '', 'S'),
 ('Jenkin, Mr. Stephen Curnow', 71, 'male', 32.0, 0, 0, 0, 2, 'C.A. 33111', 10.5, '', 'S'),
 ('Goodwin, Miss. Lillian Amy', 72, 'female', 16.0, 5, 2, 0, 3, 'CA 2144', 46.9, '', 'S'),
 ('Hood, Mr. Ambrose Jr', 73, 'male', 21.0, 0, 0, 0, 2, 'S.O.C. 14879', 73.5, '', 'S'),
 ('Chronopoulos, Mr. Apostolos', 74, 'male', 26.0, 1, 0, 0, 3, '2680', 14.4542, '', 'C'),
 ('Bing, Mr. Lee', 75, 'male', 32.0, 0, 0, 1, 3, '1601', 56.4958, '', 'S'),
 ('Moen, Mr. Sigurd Hansen', 76, 'male', 25.0, 0, 0, 0, 3, '348123', 7.65, 'F G73', 'S'),
 ('Staneff, Mr. Ivan', 77, 'male', 0.0, 0, 0, 0, 3, '349208', 7.8958, '', 'S'),
 ('Moutal, Mr. Rahamin Haim', 78, 'male', 0.0, 0, 0, 0, 3, '374746', 8.05, '', 'S'),
 ('Caldwell, Master. Alden Gates', 79, 'male', 0.83, 0, 2, 1, 2, '248738', 29.0, '', 'S'),
 ('Dowdell, Miss. Elizabeth', 80, 'female', 30.0, 0, 0, 1, 3, '364516', 12.475, '', 'S'),
 ('Waelens, Mr. Achille', 81, 'male', 22.0, 0, 0, 0, 3, '345767', 9.0, '', 'S'),
 ('Sheerlinck, Mr. Jan Baptist', 82, 'male', 29.0, 0, 0, 1, 3, '345779', 9.5, '', 'S'),
 ('McDermott, Miss. Brigdet Delia', 83, 'female', 0.0, 0, 0, 1, 3, '330932', 7.7875, '', 'Q'),
 ('Carrau, Mr. Francisco M', 84, 'male', 28.0, 0, 0, 0, 1, '113059', 47.1, '', 'S'),
 ('Ilett, Miss. Bertha', 85, 'female', 17.0, 0, 0, 1, 2, 'SO/C 14885', 10.5, '', 'S'),
 ('Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 86, 'female', 33.0, 3, 0, 1, 3, '3101278', 15.85, '', 'S'),
 ('Ford, Mr. William Neal', 87, 'male', 16.0, 1, 3, 0, 3, 'W./C. 6608', 34.375, '', 'S'),
 ('Slocovski, Mr. Selman Francis', 88, 'male', 0.0, 0, 0, 0, 3, 'SOTON/OQ 392086', 8.05, '', 'S'),
 ('Fortune, Miss. Mabel Helen', 89, 'female', 23.0, 3, 2, 1, 1, '19950', 263.0, 'C23 C25 C27', 'S'),
 ('Celotti, Mr. Francesco', 90, 'male', 24.0, 0, 0, 0, 3, '343275', 8.05, '', 'S'),
 ('Christmann, Mr. Emil', 91, 'male', 29.0, 0, 0, 0, 3, '343276', 8.05, '', 'S'),
 ('Andreasson, Mr. Paul Edvin', 92, 'male', 20.0, 0, 0, 0, 3, '347466', 7.8542, '', 'S'),
 ('Chaffee, Mr. Herbert Fuller', 93, 'male', 46.0, 1, 0, 0, 1, 'W.E.P. 5734', 61.175, 'E31', 'S'),
 ('Dean, Mr. Bertram Frank', 94, 'male', 26.0, 1, 2, 0, 3, 'C.A. 2315', 20.575, '', 'S'),
 ('Coxon, Mr. Daniel', 95, 'male', 59.0, 0, 0, 0, 3, '364500', 7.25, '', 'S'),
 ('Shorney, Mr. Charles Joseph', 96, 'male', 0.0, 0, 0, 0, 3, '374910', 8.05, '', 'S'),
 ('Goldschmidt, Mr. George B', 97, 'male', 71.0, 0, 0, 0, 1, 'PC 17754', 34.6542, 'A5', 'C'),
 ('Greenfield, Mr. William Bertram', 98, 'male', 23.0, 0, 1, 1, 1, 'PC 17759', 63.3583, 'D10 D12', 'C'),
 ('Doling, Mrs. John T (Ada Julia Bone)', 99, 'female', 34.0, 0, 1, 1, 2, '231919', 23.0, '', 'S'),
 ('Kantor, Mr. Sinai', 100, 'male', 34.0, 1, 0, 0, 2, '244367', 26.0, '', 'S'),
 ('Petranec, Miss. Matilda', 101, 'female', 28.0, 0, 0, 0, 3, '349245', 7.8958, '', 'S'),
 ('Petroff, Mr. Pastcho ("Pentcho")', 102, 'male', 0.0, 0, 0, 0, 3, '349215', 7.8958, '', 'S'),
 ('White, Mr. Richard Frasar', 103, 'male', 21.0, 0, 1, 0, 1, '35281', 77.2875, 'D26', 'S'),
 ('Johansson, Mr. Gustaf Joel', 104, 'male', 33.0, 0, 0, 0, 3, '7540', 8.6542, '', 'S'),
 ('Gustafsson, Mr. Anders Vilhelm', 105, 'male', 37.0, 2, 0, 0, 3, '3101276', 7.925, '', 'S'),
 ('Mionoff, Mr. Stoytcho', 106, 'male', 28.0, 0, 0, 0, 3, '349207', 7.8958, '', 'S'),
 ('Salkjelsvik, Miss. Anna Kristine', 107, 'female', 21.0, 0, 0, 1, 3, '343120', 7.65, '', 'S'),
 ('Moss, Mr. Albert Johan', 108, 'male', 0.0, 0, 0, 1, 3, '312991', 7.775, '', 'S'),
 ('Rekic, Mr. Tido', 109, 'male', 38.0, 0, 0, 0, 3, '349249', 7.8958, '', 'S'),
 ('Moran, Miss. Bertha', 110, 'female', 0.0, 1, 0, 1, 3, '371110', 24.15, '', 'Q'),
 ('Porter, Mr. Walter Chamberlain', 111, 'male', 47.0, 0, 0, 0, 1, '110465', 52.0, 'C110', 'S'),
 ('Zabour, Miss. Hileni', 112, 'female', 14.5, 1, 0, 0, 3, '2665', 14.4542, '', 'C'),
 ('Barton, Mr. David John', 113, 'male', 22.0, 0, 0, 0, 3, '324669', 8.05, '', 'S'),
 ('Jussila, Miss. Katriina', 114, 'female', 20.0, 1, 0, 0, 3, '4136', 9.825, '', 'S'),
 ('Attalah, Miss. Malake', 115, 'female', 17.0, 0, 0, 0, 3, '2627', 14.4583, '', 'C'),
 ('Pekoniemi, Mr. Edvard', 116, 'male', 21.0, 0, 0, 0, 3, 'STON/O 2. 3101294', 7.925, '', 'S'),
 ('Connors, Mr. Patrick', 117, 'male', 70.5, 0, 0, 0, 3, '370369', 7.75, '', 'Q'),
 ('Turpin, Mr. William John Robert', 118, 'male', 29.0, 1, 0, 0, 2, '11668', 21.0, '', 'S'),
 ('Baxter, Mr. Quigg Edmond', 119, 'male', 24.0, 0, 1, 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C'),
 ('Andersson, Miss. Ellis Anna Maria', 120, 'female', 2.0, 4, 2, 0, 3, '347082', 31.275, '', 'S'),
 ('Hickman, Mr. Stanley George', 121, 'male', 21.0, 2, 0, 0, 2, 'S.O.C. 14879', 73.5, '', 'S'),
 ('Moore, Mr. Leonard Charles', 122, 'male', 0.0, 0, 0, 0, 3, 'A4. 54510', 8.05, '', 'S'),
 ('Nasser, Mr. Nicholas', 123, 'male', 32.5, 1, 0, 0, 2, '237736', 30.0708, '', 'C'),
 ('Webber, Miss. Susan', 124, 'female', 32.5, 0, 0, 1, 2, '27267', 13.0, 'E101', 'S'),
 ('White, Mr. Percival Wayland', 125, 'male', 54.0, 0, 1, 0, 1, '35281', 77.2875, 'D26', 'S'),
 ('Nicola-Yarred, Master. Elias', 126, 'male', 12.0, 1, 0, 1, 3, '2651', 11.2417, '', 'C'),
 ('McMahon, Mr. Martin', 127, 'male', 0.0, 0, 0, 0, 3, '370372', 7.75, '', 'Q'),
 ('Madsen, Mr. Fridtjof Arne', 128, 'male', 24.0, 0, 0, 1, 3, 'C 17369', 7.1417, '', 'S'),
 ('Peter, Miss. Anna', 129, 'female', 0.0, 1, 1, 1, 3, '2668', 22.3583, 'F E69', 'C'),
 ('Ekstrom, Mr. Johan', 130, 'male', 45.0, 0, 0, 0, 3, '347061', 6.975, '', 'S'),
 ('Drazenoic, Mr. Jozef', 131, 'male', 33.0, 0, 0, 0, 3, '349241', 7.8958, '', 'C'),
 ('Coelho, Mr. Domingos Fernandeo', 132, 'male', 20.0, 0, 0, 0, 3, 'SOTON/O.Q. 3101307', 7.05, '', 'S'),
 ('Robins, Mrs. Alexander A (Grace Charity Laury)', 133, 'female', 47.0, 1, 0, 0, 3, 'A/5. 3337', 14.5, '', 'S'),
 ('Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 134, 'female', 29.0, 1, 0, 1, 2, '228414', 26.0, '', 'S'),
 ('Sobey, Mr. Samuel James Hayden', 135, 'male', 25.0, 0, 0, 0, 2, 'C.A. 29178', 13.0, '', 'S'),
 ('Richard, Mr. Emile', 136, 'male', 23.0, 0, 0, 0, 2, 'SC/PARIS 2133', 15.0458, '', 'C'),
 ('Newsom, Miss. Helen Monypeny', 137, 'female', 19.0, 0, 2, 1, 1, '11752', 26.2833, 'D47', 'S'),
 ('Futrelle, Mr. Jacques Heath', 138, 'male', 37.0, 1, 0, 0, 1, '113803', 53.1, 'C123', 'S'),
 ('Osen, Mr. Olaf Elon', 139, 'male', 16.0, 0, 0, 0, 3, '7534', 9.2167, '', 'S'),
 ('Giglio, Mr. Victor', 140, 'male', 24.0, 0, 0, 0, 1, 'PC 17593', 79.2, 'B86', 'C'),
 ('Boulos, Mrs. Joseph (Sultana)', 141, 'female', 0.0, 0, 2, 0, 3, '2678', 15.2458, '', 'C'),
 ('Nysten, Miss. Anna Sofia', 142, 'female', 22.0, 0, 0, 1, 3, '347081', 7.75, '', 'S'),
 ('Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 143, 'female', 24.0, 1, 0, 1, 3, 'STON/O2. 3101279', 15.85, '', 'S'),
 ('Burke, Mr. Jeremiah', 144, 'male', 19.0, 0, 0, 0, 3, '365222', 6.75, '', 'Q'),
 ('Andrew, Mr. Edgardo Samuel', 145, 'male', 18.0, 0, 0, 0, 2, '231945', 11.5, '', 'S'),
 ('Nicholls, Mr. Joseph Charles', 146, 'male', 19.0, 1, 1, 0, 2, 'C.A. 33112', 36.75, '', 'S'),
 ('Andersson, Mr. August Edvard ("Wennerstrom")', 147, 'male', 27.0, 0, 0, 1, 3, '350043', 7.7958, '', 'S'),
 ('Ford, Miss. Robina Maggie "Ruby"', 148, 'female', 9.0, 2, 2, 0, 3, 'W./C. 6608', 34.375, '', 'S'),
 ('Navratil, Mr. Michel ("Louis M Hoffman")', 149, 'male', 36.5, 0, 2, 0, 2, '230080', 26.0, 'F2', 'S'),
 ('Byles, Rev. Thomas Roussel Davids', 150, 'male', 42.0, 0, 0, 0, 2, '244310', 13.0, '', 'S'),
 ('Bateman, Rev. Robert James', 151, 'male', 51.0, 0, 0, 0, 2, 'S.O.P. 1166', 12.525, '', 'S'),
 ('Pears, Mrs. Thomas (Edith Wearne)', 152, 'female', 22.0, 1, 0, 1, 1, '113776', 66.6, 'C2', 'S'),
 ('Meo, Mr. Alfonzo', 153, 'male', 55.5, 0, 0, 0, 3, 'A.5. 11206', 8.05, '', 'S'),
 ('van Billiard, Mr. Austin Blyler', 154, 'male', 40.5, 0, 2, 0, 3, 'A/5. 851', 14.5, '', 'S'),
 ('Olsen, Mr. Ole Martin', 155, 'male', 0.0, 0, 0, 0, 3, 'Fa 265302', 7.3125, '', 'S'),
 ('Williams, Mr. Charles Duane', 156, 'male', 51.0, 0, 1, 0, 1, 'PC 17597', 61.3792, '', 'C'),
 ('Gilnagh, Miss. Katherine "Katie"', 157, 'female', 16.0, 0, 0, 1, 3, '35851', 7.7333, '', 'Q'),
 ('Corn, Mr. Harry', 158, 'male', 30.0, 0, 0, 0, 3, 'SOTON/OQ 392090', 8.05, '', 'S'),
 ('Smiljanic, Mr. Mile', 159, 'male', 0.0, 0, 0, 0, 3, '315037', 8.6625, '', 'S'),
 ('Sage, Master. Thomas Henry', 160, 'male', 0.0, 8, 2, 0, 3, 'CA. 2343', 69.55, '', 'S'),
 ('Cribb, Mr. John Hatfield', 161, 'male', 44.0, 0, 1, 0, 3, '371362', 16.1, '', 'S'),
 ('Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 162, 'female', 40.0, 0, 0, 1, 2, 'C.A. 33595', 15.75, '', 'S'),
 ('Bengtsson, Mr. John Viktor', 163, 'male', 26.0, 0, 0, 0, 3, '347068', 7.775, '', 'S'),
 ('Calic, Mr. Jovo', 164, 'male', 17.0, 0, 0, 0, 3, '315093', 8.6625, '', 'S'),
 ('Panula, Master. Eino Viljami', 165, 'male', 1.0, 4, 1, 0, 3, '3101295', 39.6875, '', 'S'),
 ('Goldsmith, Master. Frank John William "Frankie"', 166, 'male', 9.0, 0, 2, 1, 3, '363291', 20.525, '', 'S'),
 ('Chibnall, Mrs. (Edith Martha Bowerman)', 167, 'female', 0.0, 0, 1, 1, 1, '113505', 55.0, 'E33', 'S'),
 ('Skoog, Mrs. William (Anna Bernhardina Karlsson)', 168, 'female', 45.0, 1, 4, 0, 3, '347088', 27.9, '', 'S'),
 ('Baumann, Mr. John D', 169, 'male', 0.0, 0, 0, 0, 1, 'PC 17318', 25.925, '', 'S'),
 ('Ling, Mr. Lee', 170, 'male', 28.0, 0, 0, 0, 3, '1601', 56.4958, '', 'S'),
 ('Van der hoef, Mr. Wyckoff', 171, 'male', 61.0, 0, 0, 0, 1, '111240', 33.5, 'B19', 'S'),
 ('Rice, Master. Arthur', 172, 'male', 4.0, 4, 1, 0, 3, '382652', 29.125, '', 'Q'),
 ('Johnson, Miss. Eleanor Ileen', 173, 'female', 1.0, 1, 1, 1, 3, '347742', 11.1333, '', 'S'),
 ('Sivola, Mr. Antti Wilhelm', 174, 'male', 21.0, 0, 0, 0, 3, 'STON/O 2. 3101280', 7.925, '', 'S'),
 ('Smith, Mr. James Clinch', 175, 'male', 56.0, 0, 0, 0, 1, '17764', 30.6958, 'A7', 'C'),
 ('Klasen, Mr. Klas Albin', 176, 'male', 18.0, 1, 1, 0, 3, '350404', 7.8542, '', 'S'),
 ('Lefebre, Master. Henry Forbes', 177, 'male', 0.0, 3, 1, 0, 3, '4133', 25.4667, '', 'S'),
 ('Isham, Miss. Ann Elizabeth', 178, 'female', 50.0, 0, 0, 0, 1, 'PC 17595', 28.7125, 'C49', 'C'),
 ('Hale, Mr. Reginald', 179, 'male', 30.0, 0, 0, 0, 2, '250653', 13.0, '', 'S'),
 ('Leonard, Mr. Lionel', 180, 'male', 36.0, 0, 0, 0, 3, 'LINE', 0.0, '', 'S'),
 ('Sage, Miss. Constance Gladys', 181, 'female', 0.0, 8, 2, 0, 3, 'CA. 2343', 69.55, '', 'S'),
 ('Pernot, Mr. Rene', 182, 'male', 0.0, 0, 0, 0, 2, 'SC/PARIS 2131', 15.05, '', 'C'),
 ('Asplund, Master. Clarence Gustaf Hugo', 183, 'male', 9.0, 4, 2, 0, 3, '347077', 31.3875, '', 'S'),
 ('Becker, Master. Richard F', 184, 'male', 1.0, 2, 1, 1, 2, '230136', 39.0, 'F4', 'S'),
 ('Kink-Heilmann, Miss. Luise Gretchen', 185, 'female', 4.0, 0, 2, 1, 3, '315153', 22.025, '', 'S'),
 ('Rood, Mr. Hugh Roscoe', 186, 'male', 0.0, 0, 0, 0, 1, '113767', 50.0, 'A32', 'S'),
 ('O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 187, 'female', 0.0, 1, 0, 1, 3, '370365', 15.5, '', 'Q'),
 ('Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 188, 'male', 45.0, 0, 0, 1, 1, '111428', 26.55, '', 'S'),
 ('Bourke, Mr. John', 189, 'male', 40.0, 1, 1, 0, 3, '364849', 15.5, '', 'Q'),
 ('Turcin, Mr. Stjepan', 190, 'male', 36.0, 0, 0, 0, 3, '349247', 7.8958, '', 'S'),
 ('Pinsky, Mrs. (Rosa)', 191, 'female', 32.0, 0, 0, 1, 2, '234604', 13.0, '', 'S'),
 ('Carbines, Mr. William', 192, 'male', 19.0, 0, 0, 0, 2, '28424', 13.0, '', 'S'),
 ('Andersen-Jensen, Miss. Carla Christine Nielsine', 193, 'female', 19.0, 1, 0, 1, 3, '350046', 7.8542, '', 'S'),
 ('Navratil, Master. Michel M', 194, 'male', 3.0, 1, 1, 1, 2, '230080', 26.0, 'F2', 'S'),
 ('Brown, Mrs. James Joseph (Margaret Tobin)', 195, 'female', 44.0, 0, 0, 1, 1, 'PC 17610', 27.7208, 'B4', 'C'),
 ('Lurette, Miss. Elise', 196, 'female', 58.0, 0, 0, 1, 1, 'PC 17569', 146.5208, 'B80', 'C'),
 ('Mernagh, Mr. Robert', 197, 'male', 0.0, 0, 0, 0, 3, '368703', 7.75, '', 'Q'),
 ('Olsen, Mr. Karl Siegwart Andreas', 198, 'male', 42.0, 0, 1, 0, 3, '4579', 8.4042, '', 'S'),
 ('Madigan, Miss. Margaret "Maggie"', 199, 'female', 0.0, 0, 0, 1, 3, '370370', 7.75, '', 'Q'),
 ('Yrois, Miss. Henriette ("Mrs Harbeck")', 200, 'female', 24.0, 0, 0, 0, 2, '248747', 13.0, '', 'S'),
 ('Vande Walle, Mr. Nestor Cyriel', 201, 'male', 28.0, 0, 0, 0, 3, '345770', 9.5, '', 'S'),
 ('Sage, Mr. Frederick', 202, 'male', 0.0, 8, 2, 0, 3, 'CA. 2343', 69.55, '', 'S'),
 ('Johanson, Mr. Jakob Alfred', 203, 'male', 34.0, 0, 0, 0, 3, '3101264', 6.4958, '', 'S'),
 ('Youseff, Mr. Gerious', 204, 'male', 45.5, 0, 0, 0, 3, '2628', 7.225, '', 'C'),
 ('Cohen, Mr. Gurshon "Gus"', 205, 'male', 18.0, 0, 0, 1, 3, 'A/5 3540', 8.05, '', 'S'),
 ('Strom, Miss. Telma Matilda', 206, 'female', 2.0, 0, 1, 0, 3, '347054', 10.4625, 'G6', 'S'),
 ('Backstrom, Mr. Karl Alfred', 207, 'male', 32.0, 1, 0, 0, 3, '3101278', 15.85, '', 'S'),
 ('Albimona, Mr. Nassef Cassem', 208, 'male', 26.0, 0, 0, 1, 3, '2699', 18.7875, '', 'C'),
 ('Carr, Miss. Helen "Ellen"', 209, 'female', 16.0, 0, 0, 1, 3, '367231', 7.75, '', 'Q'),
 ('Blank, Mr. Henry', 210, 'male', 40.0, 0, 0, 1, 1, '112277', 31.0, 'A31', 'C'),
 ('Ali, Mr. Ahmed', 211, 'male', 24.0, 0, 0, 0, 3, 'SOTON/O.Q. 3101311', 7.05, '', 'S'),
 ('Cameron, Miss. Clear Annie', 212, 'female', 35.0, 0, 0, 1, 2, 'F.C.C. 13528', 21.0, '', 'S'),
 ('Perkin, Mr. John Henry', 213, 'male', 22.0, 0, 0, 0, 3, 'A/5 21174', 7.25, '', 'S'),
 ('Givard, Mr. Hans Kristensen', 214, 'male', 30.0, 0, 0, 0, 2, '250646', 13.0, '', 'S'),
 ('Kiernan, Mr. Philip', 215, 'male', 0.0, 1, 0, 0, 3, '367229', 7.75, '', 'Q'),

## 4) Commandes de réinitialisations

In [17]:
%%sql
delete from survivant;
delete from passager;
delete from ticket;

 * postgresql://user1:***@localhost/postgres
1 rows affected.
1 rows affected.
1 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [43]:
%%sql
drop table survivant;
drop table passager;
drop table ticket;

 * postgresql://user1:***@localhost/postgres
Done.
Done.
Done.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

# 5) Script sous format texte

--Réinitialisation

drop table survivant;
drop table passager;
drop table ticket;

--Creation des tables

CREATE TABLE ticket(Name varchar(100) primary key, Pclass int, Ticket varchar(20), 
                    Fare float, Cabin varchar(20), Embarked varchar(1));

CREATE TABLE passager(PassengerId int primary key, Name varchar(100), Sex varchar(6), Age float, SibSp int, Parch int, 
                      foreign key (Name) references ticket(Name));

CREATE TABLE survivant(PassengerId int, Name varchar(100), Survived int, 
                       foreign key (PassengerId) references passager(passengerid),
                       foreign key (Name) references ticket(name));

SELECT * from ticket;
SELECT * from passager;
SELECT * from survivant;
SELECT * from passager natural join survivant natural join ticket;

--Exemple avec le passager n°1

INSERT INTO ticket VALUES ('Braund, Mr. Owen Harris', 3, 'A/5 21171', 7.25, null, 'S');
INSERT INTO passager VALUES (1,(select name from ticket), 'male', 22, 1, 0);
INSERT INTO survivant VALUES ((select passengerid from passager),(select name from ticket),0);

SELECT * from ticket;
SELECT * from passager;
SELECT * from survivant;
SELECT * from passager natural join survivant natural join ticket;

--Alimentation avec données titanic_train.csv

\copy ticket from '/Users/Asus/Documents/ticket.txt'
\copy passager from '/Users/Asus/Documents/passager.txt'
\copy survivant from '/Users/Asus/Documents/survivant.txt'


SELECT * from ticket;
SELECT * from passager;
SELECT * from survivant;
SELECT * from passager natural join survivant natural join ticket;